// LE CLOSING — bibliothèque de deals réels
// Format : {id, title, tag, year, place, story[], questions:[{q, opts, a, exp}], lesson}
const DEALS = [
{
id:"rjr", title:"RJR Nabisco", tag:"LBO", year:"1988", place:"États-Unis",
story:[
"1988. Ross Johnson, PDG de RJR Nabisco (cigarettes Camel, biscuits Oreo), vit comme un roi : dix jets privés, terrains de golf, salaires démesurés. Le cours de bourse stagne et Johnson a une idée : racheter sa propre boîte avec de la dette — un MBO (management buyout) — à 75 $ l'action, pour la sortir de la cote et s'enrichir au passage.",
"Problème : en annonçant son offre, il met officiellement la société en vente. KKR, le fonds pionnier du LBO mené par Henry Kravis, entre dans la bataille. S'ensuit la guerre d'enchères la plus célèbre de l'histoire : offres, contre-offres, trahisons, banquiers de Wall Street qui se déchirent. KKR l'emporte à 109 $ l'action, soit 25 milliards de dollars — le plus gros LBO du monde pendant 17 ans.",
"Le montage : environ 1 à 2 milliards de fonds propres seulement, le reste en dette, dont une montagne de junk bonds placés par Drexel Burnham. La suite est douloureuse : le fardeau de la dette écrase l'entreprise, les taux montent, le marché du tabac se retourne (guerre des prix Marlboro, 1993). KKR sortira des années plus tard avec un rendement quasi nul. Le deal a donné un livre culte, « Barbarians at the Gate », et une leçon éternelle : gagner l'enchère n'est pas gagner le deal."
],
questions:[
{q:"Pourquoi l'offre de Ross Johnson a-t-elle déclenché une guerre d'enchères ?", opts:["Parce qu'elle était trop haute","Parce qu'une offre de MBO met de facto la société en vente : le conseil doit chercher le meilleur prix pour les actionnaires","Parce que KKR détenait déjà 20 % du capital","Parce que la loi américaine impose deux offres concurrentes"], a:1, exp:"Dès qu'un dirigeant propose de racheter sa société, le conseil d'administration a un devoir fiduciaire : maximiser le prix pour les actionnaires. Il doit donc ouvrir la porte aux offres concurrentes."},
{q:"Qu'est-ce qui caractérise le financement d'un LBO comme celui de RJR ?", opts:["Beaucoup de fonds propres, peu de dette","Uniquement des actions nouvelles","Une part de fonds propres faible et une dette massive, remboursée par les cash-flows de la cible elle-même","Un financement 100 % public"], a:2, exp:"C'est le principe du Leveraged Buyout : l'acquéreur apporte peu d'equity, emprunte le reste, et c'est la cible qui rembourse la dette avec ses propres cash-flows. L'effet de levier démultiplie le rendement… et le risque."},
{q:"Qu'est-ce qu'un junk bond (obligation à haut rendement) ?", opts:["Une obligation d'État à taux négatif","Une obligation émise par un émetteur risqué, notée en dessous d'investment grade, qui paie un taux élevé pour compenser","Une action préférentielle","Une dette bancaire senior classique"], a:1, exp:"Notation inférieure à BBB- : risque de défaut élevé, donc rendement élevé. Drexel Burnham et Michael Milken en avaient fait le carburant des LBO des années 80."},
{q:"Quelle est la leçon finale de RJR Nabisco pour un investisseur ?", opts:["Il faut toujours surenchérir pour gagner","Le tabac est un mauvais secteur","La malédiction du vainqueur : payer trop cher détruit le rendement même si l'enchère est gagnée","Les MBO sont interdits depuis"], a:2, exp:"KKR a gagné la bataille mais quasiment rien gagné financièrement : à 109 $ l'action, le prix intégrait déjà tout l'upside. C'est la « winner's curse » : dans une enchère, le vainqueur est souvent celui qui a le plus surpayé."}
],
lesson:"Le prix d'achat est le premier déterminant du rendement. Une enchère gagnée à n'importe quel prix est une défaite déguisée."
},
{
id:"aoltw", title:"AOL – Time Warner", tag:"Fusion", year:"2000", place:"États-Unis",
story:[
"Janvier 2000, sommet de la bulle internet. AOL, fournisseur d'accès à internet valorisé 165 milliards de dollars, annonce la fusion avec Time Warner, empire des médias (CNN, Warner Bros, Time). Valeur combinée : 350 milliards. La presse parle du « deal du siècle » : les tuyaux d'internet épousent les contenus.",
"Détail crucial : AOL paie en actions. Ses propres actions, gonflées par la bulle, servent de monnaie. Les actionnaires d'AOL obtiennent 55 % du nouvel ensemble alors que Time Warner génère l'essentiel des profits réels. Steve Case, patron d'AOL, a compris que son papier surévalué n'aurait jamais autant de valeur : il l'échange contre des actifs tangibles avant que la musique s'arrête.",
"Deux mois plus tard, la bulle éclate. Les abonnés AOL fuient vers le haut débit, la pub en ligne s'effondre. En 2002, le groupe passe une dépréciation de goodwill de 99 milliards de dollars — la plus grosse perte comptable de l'histoire américaine à l'époque. Le goodwill, c'est l'écart entre le prix payé et la valeur des actifs identifiables : quand la cible ne vaut plus ce qu'on l'a payée, on le déprécie, et la perte traverse le compte de résultat. En 2009, AOL est finalement scindée, valorisée à peine 3 milliards. Time Warner avait vendu son âme contre du papier."
],
questions:[
{q:"Pourquoi payer en actions plutôt qu'en cash était-il stratégique pour AOL ?", opts:["Le cash était fiscalement pénalisé","Ses actions étaient massivement surévaluées : les échanger contre des actifs réels revenait à vendre au sommet","Time Warner refusait le cash","Les banques ne prêtaient plus en 2000"], a:1, exp:"Quand ta monnaie d'acquisition (ton action) est surévaluée, payer en titres transfère le risque de correction aux actionnaires de la cible. Signal classique : une entreprise qui paie en actions pense souvent que son cours est au plus haut."},
{q:"Qu'est-ce que le goodwill dans un bilan post-acquisition ?", opts:["La trésorerie de la cible","L'écart entre le prix d'acquisition et la juste valeur des actifs nets identifiables de la cible","Les synergies réalisées","Une réserve légale obligatoire"], a:1, exp:"Tu paies 100 pour une société dont les actifs nets identifiables valent 40 : les 60 de différence s'inscrivent en goodwill. Il matérialise ce que tu as payé pour les synergies espérées, la marque, la position de marché… ou ton excès d'optimisme."},
{q:"Que signifie une dépréciation (impairment) de goodwill de 99 Md$ ?", opts:["Une sortie de cash de 99 Md$","L'aveu comptable que l'acquisition ne vaut pas ce qui a été payé : perte au compte de résultat, sans sortie de cash","Une amende du régulateur","Un remboursement aux actionnaires"], a:1, exp:"L'impairment est non-cash : aucun euro ne sort. Mais c'est l'aveu public que la valeur a été détruite au moment de l'acquisition. Le cash, lui, avait été détruit le jour de la signature."},
{q:"Quel signal d'alerte les administrateurs de Time Warner ont-ils ignoré ?", opts:["La différence entre valorisation boursière et profits réels : AOL valait plus que Time Warner en bourse mais gagnait beaucoup moins","La taille du deal","L'absence de banques conseil","Le manque de couverture presse"], a:0, exp:"AOL pesait 55 % du deal grâce à un multiple délirant sur des profits fragiles. Quand la parité d'échange repose sur des valorisations de bulle plutôt que sur les fondamentaux (cash-flows), la partie qui apporte les vrais profits se fait diluer."}
],
lesson:"Regarde toujours avec quoi on te paie. Une action surévaluée est une fausse monnaie : la parité d'échange doit se juger sur les cash-flows, pas sur les cours de bourse."
},
{
id:"vivendi", title:"Vivendi Universal — la chute de Messier", tag:"Conglomérat", year:"2000-2002", place:"France",
story:[
"Jean-Marie Messier, X-ENA, star du capitalisme français, transforme en quelques années la Compagnie Générale des Eaux — distribution d'eau, activité ennuyeuse mais génératrice de cash — en Vivendi Universal : Canal+, Universal Music, studios hollywoodiens, télécoms. Plus de 100 milliards de dollars d'acquisitions, souvent payées au sommet de la bulle. « J6M » (Jean-Marie Messier Moi-Même Maître du Monde) s'installe à New York.",
"Le problème est enfoui dans les comptes : Vivendi publie des résultats flatteurs en EBITDA proforma, mais le cash ne suit pas. Les acquisitions sont payées en partie en dette, les participations sont enchevêtrées, et le groupe a signé des engagements de rachat et des puts qui peuvent exiger du cash à tout moment. Été 2002 : la confiance casse, les agences dégradent la note, les lignes de crédit se ferment. Vivendi, géant de 60 milliards de chiffre d'affaires, manque de trésorerie pour passer l'été. Messier est débarqué en juillet.",
"Son successeur Jean-René Fourtou vend en urgence des actifs pour éteindre l'incendie. La perte 2002 : 23 milliards d'euros, record français. La leçon tient en une phrase devenue proverbe : le résultat net est une opinion, le cash est un fait. Un groupe peut afficher des profits et mourir de soif."
],
questions:[
{q:"Quelle distinction fondamentale la chute de Vivendi illustre-t-elle ?", opts:["Résultat comptable et trésorerie sont deux choses différentes : on peut afficher un EBITDA flatteur et faire défaut faute de cash","Les conglomérats sont toujours rentables","La dette est préférable aux fonds propres","Les médias sont plus rentables que l'eau"], a:0, exp:"L'EBITDA proforma de Vivendi masquait des sorties de cash massives (capex, engagements, puts). La solvabilité se lit au tableau de flux de trésorerie et à l'échéancier de dette, pas au compte de résultat."},
{q:"Qu'est-ce qu'une crise de liquidité, par opposition à une crise de solvabilité ?", opts:["Les deux sont identiques","La liquidité : incapacité à honorer les échéances immédiates même avec des actifs de valeur ; la solvabilité : les actifs ne couvrent plus les dettes","La liquidité concerne les banques uniquement","La solvabilité est un problème de court terme"], a:1, exp:"Vivendi possédait des actifs magnifiques (Universal Music !) mais ne pouvait pas les vendre assez vite pour payer ses échéances. Illiquide mais pas insolvable — sauf que sur les marchés, l'illiquidité tue avant qu'on ait le temps de prouver sa solvabilité."},
{q:"Pourquoi la dégradation de la note de crédit a-t-elle été l'étincelle fatale ?", opts:["Elle a fait chuter le cours de bourse","Elle a déclenché des clauses (ratings triggers) exigeant remboursements ou collatéral immédiats, et fermé l'accès au marché de la dette court terme","Elle a forcé la démission du conseil","Elle a annulé les acquisitions passées"], a:1, exp:"Beaucoup de financements contenaient des clauses liées à la notation : en dessous d'un seuil, remboursement anticipé ou dépôt de collatéral. La dégradation transforme un problème de confiance en besoin de cash immédiat — la spirale."},
{q:"Quel biais psychologique la trajectoire de Messier illustre-t-elle le mieux ?", opts:["L'aversion au risque","L'hubris du dirigeant : la réussite passée nourrit une confiance excessive que plus personne n'ose contester","La paralysie décisionnelle","Le biais de statu quo"], a:1, exp:"Conseil d'administration complaisant, presse conquise, égo en roue libre : plus personne ne challengeait les acquisitions. Un board qui ne dit jamais non est un facteur de risque au même titre qu'un covenant."}
],
lesson:"Le résultat est une opinion, le cash est un fait. Toujours vérifier l'échéancier de dette et les clauses cachées (puts, ratings triggers) avant de juger la santé d'un groupe."
},
{
id:"alstom", title:"Alstom – General Electric", tag:"M&A souverain", year:"2014-2015", place:"France",
story:[
"Avril 2014 : la presse révèle que GE négocie en secret le rachat de la branche énergie d'Alstom — les turbines qui équipent les centrales nucléaires françaises. Séisme politique : Alstom, c'est le TGV, les turbines Arabelle, un fleuron industriel. Arnaud Montebourg, ministre de l'Économie, découvre le deal dans la presse et entre en guerre.",
"L'État sort une arme : le décret du 14 mai 2014, dit « décret Montebourg », qui étend le contrôle des investissements étrangers aux secteurs stratégiques (énergie, eau, transports, santé, télécoms). Toute prise de contrôle étrangère y devient soumise à autorisation de Bercy. GE doit renégocier : alliances symboliques, promesses de créer 1 000 emplois, entrée de l'État au capital d'Alstom via un prêt d'actions Bouygues. Le deal se fait fin 2015, pour 12,4 milliards d'euros.",
"L'arrière-plan est plus sombre : depuis 2013, la justice américaine (DOJ) poursuivait Alstom pour corruption au titre du FCPA, loi américaine à portée extraterritoriale. Un cadre dirigeant, Frédéric Pierucci, est incarcéré aux États-Unis. Alstom paiera 772 millions de dollars d'amende. Beaucoup y voient un levier de négociation américain — la thèse du livre « Le Piège américain ». Épilogue ironique : les promesses d'emplois ne sont pas tenues, GE Energy périclite, et EDF rachète les turbines Arabelle en 2022. L'État avait vendu, il rachète sept ans plus tard."
],
questions:[
{q:"Qu'est-ce que le contrôle des investissements étrangers (régime IEF en France) ?", opts:["Une taxe sur les acquéreurs étrangers","Un régime d'autorisation préalable de Bercy pour toute prise de contrôle étrangère dans les secteurs stratégiques","Une interdiction totale des rachats étrangers","Un simple avis consultatif"], a:1, exp:"Dans les secteurs listés (défense, énergie, santé, données, etc.), l'acquéreur étranger doit obtenir l'autorisation du ministère de l'Économie, qui peut imposer des conditions ou refuser. Depuis élargi et renforcé (seuil abaissé à 10 % pour les sociétés cotées en 2020)."},
{q:"Qu'est-ce que le FCPA et pourquoi frappe-t-il une entreprise française ?", opts:["Une norme comptable européenne","La loi anticorruption américaine, applicable dès qu'il existe un lien avec les États-Unis (dollar, serveurs, filiale) — portée extraterritoriale","Un traité bilatéral franco-américain","Une règle boursière d'Euronext"], a:1, exp:"Le Foreign Corrupt Practices Act permet au DOJ de poursuivre des entreprises étrangères pour corruption si un lien même ténu avec les États-Unis existe (paiement en dollars, email transitant par un serveur US). Arme juridique redoutable, que la France a tenté de contrer avec la loi Sapin 2."},
{q:"Dans une négociation M&A, que change l'irruption de l'État comme partie prenante ?", opts:["Rien, seul le prix compte","Le deal devient multidimensionnel : emplois, souveraineté, gouvernance et engagements sociaux pèsent autant que le prix ; le calendrier et la certitude d'exécution se dégradent","L'État paie toujours une prime","Le deal devient automatiquement public"], a:1, exp:"Face à un acteur politique, la valeur ne se mesure plus seulement en euros : engagements d'emploi, comités de suivi, golden share, co-entreprises symboliques. Pour l'acquéreur, chaque concession non financière achète la certitude de closing."},
{q:"Quelle leçon de long terme l'épilogue (rachat des turbines par EDF en 2022) enseigne-t-il ?", opts:["Les cessions d'actifs stratégiques peuvent coûter cher à racheter : la réversibilité d'un deal souverain est une illusion","GE a fait une bonne affaire","Les turbines n'étaient pas stratégiques","L'État ne devrait jamais intervenir"], a:0, exp:"Vendre un actif stratégique se fait en un deal ; le reconstituer prend une décennie et coûte une prime. En M&A souverain, l'analyse doit intégrer le coût de re-création de la capacité perdue, pas seulement le prix de cession."}
],
lesson:"Un deal n'est pas qu'un prix : parties prenantes, géopolitique et exécution peuvent peser plus que la valorisation. Et une amende extraterritoriale peut être une arme de négociation."
},
{
id:"lvmh", title:"LVMH – Tiffany", tag:"MAC clause", year:"2019-2021", place:"France / États-Unis",
story:[
"Novembre 2019 : LVMH signe le rachat de Tiffany & Co., le joaillier new-yorkais aux boîtes bleues, pour 16,2 milliards de dollars — 135 $ par action, en cash. Plus grosse acquisition de l'histoire du luxe. Bernard Arnault veut renforcer LVMH dans la joaillerie face à Cartier (Richemont).",
"Mars 2020 : le Covid ferme les boutiques du monde entier. Tiffany, très dépendante des touristes et des centres commerciaux américains, souffre. Arnault, surnommé « le loup en cachemire », cherche la sortie : en septembre 2020, LVMH annonce qu'il ne peut plus closer le deal, invoquant une lettre du Quai d'Orsay demandant de reporter l'acquisition (défense diplomatique inédite) et une clause de « material adverse effect » (MAE/MAC) : un changement défavorable significatif affectant durablement la cible.",
"Tiffany attaque devant la Chancery Court du Delaware, le tribunal roi du M&A américain. Problème pour LVMH : les MAC sont interprétées de façon très restrictive — une pandémie mondiale frappant tout le secteur n'est généralement pas un MAC si le contrat ne l'exclut pas explicitement, et Tiffany n'était pas touchée « de manière disproportionnée ». Plutôt que de risquer un procès perdu, les parties renégocient : 131,5 $ par action au lieu de 135 $. Rabais : environ 430 millions de dollars, moins de 3 %. Le deal close en janvier 2021. Depuis, Tiffany a doublé ses profits sous pavillon LVMH : le loup avait raison de vouloir la proie, même au prix fort."
],
questions:[
{q:"Qu'est-ce qu'une clause MAC (material adverse change) dans un contrat d'acquisition ?", opts:["Une clause de révision automatique du prix","Une clause permettant à l'acquéreur de ne pas closer si un événement défavorable significatif et durable frappe la cible entre signing et closing","Une garantie donnée par le vendeur sur ses comptes","Une clause de non-concurrence"], a:1, exp:"Entre la signature (signing) et la réalisation (closing), des mois passent. La MAC protège l'acquéreur contre un effondrement de la cible pendant cette période. Mais les tribunaux l'interprètent très strictement : il faut un impact grave, durable et souvent disproportionné par rapport au secteur."},
{q:"Pourquoi le Covid n'était-il probablement pas un MAC valable ici ?", opts:["Parce que le Covid était fini en 2020","Parce qu'un choc frappant tout le secteur, sans impact disproportionné sur la cible, entre dans les risques systémiques que l'acquéreur assume — sauf exclusion contractuelle explicite","Parce que Tiffany avait caché ses comptes","Parce que la clause n'existait pas dans le contrat"], a:1, exp:"La jurisprudence du Delaware (affaire Akorn, seul MAC reconnu en 2018, pour un effondrement spécifique et durable de la cible) exige un effet disproportionné. Une pandémie mondiale touche tout le luxe : LVMH assumait ce risque de marché."},
{q:"Pourquoi les deals M&A américains se jugent-ils si souvent au Delaware ?", opts:["Les impôts y sont nuls","La majorité des grandes sociétés US y sont immatriculées et sa Chancery Court offre une jurisprudence spécialisée, rapide et prévisible en droit des sociétés","C'est une obligation fédérale","Les juges y sont élus par les entreprises"], a:1, exp:"Plus de 60 % des sociétés du Fortune 500 sont incorporées au Delaware. Sa Court of Chancery, sans jury, avec des juges ultra-spécialisés, rend le contentieux M&A prévisible — ce que les praticiens valorisent par-dessus tout."},
{q:"Que révèle le rabais final de moins de 3 % sur le rapport de force ?", opts:["Que LVMH a gagné le procès","Que la menace juridique de LVMH était faible : le rabais est le prix d'une sortie de crise sans procès, pas la reconnaissance d'un MAC","Que Tiffany était en faillite","Que le Quai d'Orsay a fixé le prix"], a:1, exp:"Si le MAC avait été solide, LVMH aurait obtenu bien plus (ou serait sorti du deal). 430 M$ sur 16 Md$, c'est un geste de face-saving : chacun évite le risque du procès, Arnault affiche une victoire, Tiffany sécurise son closing."}
],
lesson:"Entre signing et closing, le risque appartient à celui que le contrat désigne. Une MAC se négocie mot par mot : exclusions (pandémie, guerre, marché) et « effet disproportionné » font toute la différence."
},
{
id:"wirecard", title:"Wirecard — les 1,9 milliard fantômes", tag:"Fraude", year:"2020", place:"Allemagne",
story:[
"Wirecard, fintech bavaroise de paiement, est la fierté de l'Allemagne : entrée au DAX 30 en 2018 à la place de Commerzbank, valorisée jusqu'à 24 milliards d'euros. Son patron Markus Braun, en col roulé façon Steve Jobs, promet une croissance sans fin portée par des filiales asiatiques ultra-rentables.",
"Depuis 2015, le Financial Times, mené par le journaliste Dan McCrum, publie des enquêtes accablantes : les profits asiatiques semblent fictifs, gonflés par un « third-party acquiring » invérifiable. Réaction stupéfiante du régulateur allemand, la BaFin : au lieu d'enquêter sur Wirecard, elle interdit la vente à découvert du titre et porte plainte… contre les journalistes. Les auditeurs d'EY, eux, certifient les comptes année après année sans jamais vérifier directement les soldes bancaires aux Philippines — ils se contentaient de confirmations fournies par des tiers.",
"Juin 2020 : sous la pression d'un audit spécial KPMG, EY exige enfin la preuve des dépôts. Les deux banques philippines censées détenir 1,9 milliard d'euros répondent : ces comptes n'existent pas. En quelques jours, Wirecard avoue que l'argent « n'existe probablement pas », dépose le bilan — première faillite d'un membre du DAX — et son directeur des opérations Jan Marsalek s'enfuit ; on le retrouvera des années plus tard caché en Russie, soupçonné de liens avec les services russes. Les vendeurs à découvert, insultés pendant cinq ans, avaient raison depuis le début."
],
questions:[
{q:"Quel principe d'audit élémentaire EY a-t-il négligé pendant des années ?", opts:["Le contrôle des notes de frais","La confirmation directe et indépendante des soldes bancaires auprès des banques elles-mêmes","La vérification des contrats clients","Le comptage des stocks"], a:1, exp:"La circularisation bancaire — demander directement à la banque de confirmer le solde — est un geste d'audit de première année. EY a accepté des documents fournis par un trustee tiers. 1,9 Md€, soit environ un quart du bilan, n'a jamais été vérifié à la source."},
{q:"Que nous apprend la réaction de la BaFin (plainte contre les journalistes, interdiction du short) ?", opts:["Les régulateurs ont toujours raison","Le biais du champion national : le régulateur a défendu « sa » fintech contre les critiques au lieu d'enquêter — les vendeurs à découvert et la presse sont des signaux, pas des ennemis","Le short selling est illégal en Europe","Le FT était payé par des concurrents"], a:1, exp:"Quand une entreprise attaquée répond en attaquant les messagers (journalistes, shorts) et que le régulateur l'y aide par fierté nationale, le signal d'alarme redouble. Les short sellers font un pari coûteux : leur conviction mérite examen, pas mépris."},
{q:"Quel red flag comptable les analystes attentifs pouvaient-ils voir ?", opts:["Des profits élevés mais concentrés dans des filiales opaques et invérifiables, avec un cash qui ne remonte jamais à la maison mère","Un dividende trop généreux","Une marque trop connue","Des bureaux trop luxueux"], a:0, exp:"Profits mirifiques logés dans des entités lointaines, auditées localement par de petits cabinets, cash « en trust » jamais disponible : structure classique de fraude. Si les profits sont réels, le cash finit par remonter. S'il ne remonte jamais, doute."},
{q:"Pour un financier, quelle est la meilleure protection contre un Wirecard en portefeuille ?", opts:["Faire confiance à la notation","Croiser le narratif avec les flux de trésorerie réels, lire les critiques argumentées (short reports, presse), et se méfier des entreprises qui répondent aux questions par des procès","Suivre l'indice, le DAX ne peut pas se tromper","Rencontrer le PDG"], a:1, exp:"L'appartenance à un indice, la certification d'un Big Four et l'aval d'un régulateur n'ont rien empêché. La défense, c'est le scepticisme méthodique : cash-flow vs résultat, sources critiques, et attention aux managements procéduriers."}
],
lesson:"Ni l'auditeur, ni le régulateur, ni l'indice ne te protègent. Quand les profits ne se transforment jamais en cash disponible et que l'entreprise attaque ses critiques, sors."
},
{
id:"kraftheinz", title:"Kraft-Heinz et 3G — le mirage des synergies", tag:"Synergies", year:"2015-2019", place:"États-Unis / Brésil",
story:[
"3G Capital, le fonds brésilien de Jorge Paulo Lemann, a une méthode devenue légendaire : racheter des marques de consommation installées, tailler dans les coûts avec le « zero-based budgeting » (chaque dépense doit être rejustifiée depuis zéro chaque année), et empiler les acquisitions. Avec Warren Buffett en partenaire, 3G orchestre en 2015 la fusion Kraft-Heinz : 49 milliards de dollars, troisième groupe agroalimentaire d'Amérique du Nord.",
"Les premières années éblouissent Wall Street : les marges d'EBITDA bondissent de 20 % à 26 %, du jamais vu dans le secteur. Mais la machine a un angle mort : on ne coupe pas indéfiniment dans le marketing, la R&D et la qualité sans tuer ce qui fait la valeur d'une marque. Pendant que Kraft-Heinz coupe, les consommateurs migrent vers le frais, le bio, les marques de distributeurs. Les volumes s'érodent, le pricing power s'évapore.",
"Février 2019, la facture tombe : dépréciation de 15,4 milliards de dollars sur les marques Kraft et Oscar Mayer, dividende coupé, enquête de la SEC sur la comptabilité des achats. L'action perd 27 % en un jour. Buffett reconnaîtra publiquement : « Nous avons surpayé Kraft. » La leçon vaut pour tous les modèles à synergies : les économies de coûts sont réelles une fois ; l'érosion de la marque est éternelle."
],
questions:[
{q:"Qu'est-ce que le zero-based budgeting (ZBB) ?", opts:["Un budget sans trésorerie","Une méthode où chaque ligne de dépense doit être rejustifiée depuis zéro à chaque cycle, au lieu de reconduire le budget précédent","Un gel des embauches","Une comptabilité sans provisions"], a:1, exp:"Le ZBB casse la logique du « budget de l'an dernier +3 % ». Redoutablement efficace pour purger les coûts superflus — mais appliqué sans discernement, il coupe aussi le muscle (marketing, R&D, qualité) avec la graisse."},
{q:"Pourquoi les synergies de coûts ont-elles un rendement décroissant ?", opts:["Elles augmentent les impôts","Les premières coupes éliminent le superflu, les suivantes attaquent les fonctions qui créent la valeur : marque, innovation, relation client","Elles sont interdites au-delà de 10 %","Les salariés votent contre"], a:1, exp:"Une marge qui passe de 20 % à 26 % en trois ans dans un secteur mature doit interroger : d'où vient l'argent ? Si c'est du sous-investissement déguisé, la marge d'aujourd'hui est le chiffre d'affaires perdu de demain."},
{q:"Que signale une dépréciation de 15,4 Md$ sur des marques (intangibles) ?", opts:["Un simple ajustement technique sans signification","L'aveu que les cash-flows futurs attendus des marques sont durablement inférieurs aux hypothèses payées à l'acquisition","Une fraude certaine","Un changement de normes comptables"], a:1, exp:"Les marques inscrites au bilan sont testées chaque année : si les flux futurs actualisés ne justifient plus la valeur comptable, on déprécie. C'est le passé (le surpaiement) qui rattrape le présent, et souvent un signal que le business se dégrade structurellement."},
{q:"Quelle erreur d'analyse Wall Street a-t-elle commise entre 2015 et 2018 ?", opts:["Extrapoler des marges records comme durables sans se demander si elles étaient financées par du sous-investissement dans la marque","Sous-estimer les synergies","Ignorer les taux d'intérêt","Mal calculer le BFR"], a:0, exp:"Le marché a valorisé Kraft-Heinz sur des marges de pointe supposées permanentes. Toujours se demander : cette marge est-elle le fruit d'un avantage compétitif ou d'une récolte (harvesting) qui épuise l'actif ? La deuxième ne mérite pas un multiple élevé."}
],
lesson:"Les synergies de coûts se réalisent une fois ; une marque détruite ne revient pas. Une marge anormalement haute doit être expliquée avant d'être extrapolée."
},
{
id:"twitter", title:"Musk – Twitter : 44 milliards, à contrecœur", tag:"LBO / Contentieux", year:"2022", place:"États-Unis",
story:[
"Avril 2022 : Elon Musk, après être monté discrètement à 9 % du capital, offre de racheter Twitter à 54,20 $ l'action — 44 milliards de dollars, cash. Clin d'œil au « 420 » de la culture cannabis : le sérieux du prix laisse perplexe, mais l'offre est réelle, financée par sa fortune Tesla et 13 milliards de dette bancaire. Le conseil de Twitter, d'abord hostile (il déploie une poison pill), accepte face à la prime. Le merger agreement est signé fin avril, quasiment sans due diligence — Musk y a renoncé.",
"Mai 2022 : les marchés chutent, Tesla dévisse, et les 44 milliards paraissent soudain très chers. Musk cherche la sortie : il accuse Twitter de mentir sur la proportion de bots et prétend résilier l'accord. Twitter l'attaque au Delaware en « specific performance » : le contrat prévoit que le vendeur peut exiger l'exécution forcée du deal, pas seulement des dommages. Or l'accord signé est béton : pas de condition de financement, pas de due diligence, break-up fee d'un milliard ne permettant pas de s'échapper à volonté.",
"Face à un procès perdu d'avance — les emails révélés au fil de la procédure sont accablants —, Musk capitule en octobre et paie le prix plein. Les banques, coincées avec 13 milliards de dette devenue invendable, la garderont des années sur leurs bilans avec des pertes lourdes. Morale en deux temps : on ne signe pas un contrat de 44 milliards en pariant qu'on pourra le déchirer ; et la dette d'un LBO signé au sommet du marché devient le problème des banques."
],
questions:[
{q:"Qu'est-ce que la « specific performance » qui a piégé Musk ?", opts:["Une pénalité financière plafonnée","Le droit d'exiger en justice l'exécution forcée du contrat lui-même — closer le deal — plutôt que de simples dommages-intérêts","Un audit de performance de la cible","Une clause de earn-out"], a:1, exp:"Beaucoup croyaient que Musk pouvait payer le break-up fee d'1 Md$ et partir. Faux : le fee ne s'applique qu'à des cas précis (échec du financement, refus antitrust). Le contrat donnait à Twitter le droit d'exiger le closing à 54,20 $. C'est la clause qui a tout décidé."},
{q:"Pourquoi renoncer à la due diligence était-il si dangereux ?", opts:["C'est illégal","Sans DD, impossible d'invoquer ensuite des découvertes défavorables : Musk a accepté la cible « en l'état », bots compris","La DD est toujours gratuite","Cela annule le contrat"], a:1, exp:"La due diligence sert à découvrir les problèmes avant de signer et à calibrer prix et garanties. Y renoncer pour aller vite, c'est renoncer à ses munitions contentieuses : l'argument des bots était mort-né car le risque avait été contractuellement assumé."},
{q:"Qu'est-ce qu'une poison pill (pilule empoisonnée) ?", opts:["Une clause pénale dans le SPA","Un mécanisme de défense anti-OPA : au-delà d'un seuil de détention, les autres actionnaires peuvent acheter des actions à prix cassé, diluant massivement l'assaillant","Une dette cachée","Un veto de l'État"], a:1, exp:"Le rights plan rend une prise de contrôle rampante prohibitive : franchir le seuil (souvent 10-15 %) déclenche une dilution punitive. Ça force l'assaillant à négocier avec le conseil plutôt qu'à ramasser les actions en bourse."},
{q:"Pourquoi les banques ont-elles gardé les 13 Md$ de dette sur leurs bilans avec des pertes ?", opts:["Elles y étaient obligées par la Fed","Elles s'étaient engagées à financer à des conditions fixées en avril ; le marché s'étant retourné, revendre cette dette n'était possible qu'avec une forte décote — la « hung debt »","Musk a refusé de payer les intérêts","La dette était en euros"], a:1, exp:"Dans un LBO, les banques s'engagent (committed financing) puis syndiquent la dette. Si le marché se retourne entre l'engagement et la syndication, personne n'achète au pair : les banques gardent le papier (hung deal) ou vendent à perte. Le risque de marché entre signing et closing existe aussi pour les prêteurs."}
],
lesson:"Un merger agreement est une arme chargée : conditions suspensives, break-up fee et specific performance déterminent qui est piégé. Lis les clauses de sortie avant de signer, pas après."
},
{
id:"abisab", title:"AB InBev – SABMiller : le mégadeal antitrust", tag:"Antitrust", year:"2015-2016", place:"Belgique / Royaume-Uni",
story:[
"2015 : AB InBev, numéro un mondial de la bière (Budweiser, Stella Artois, Corona), déjà produit d'une cascade de fusions orchestrées par 3G Capital, lance l'assaut sur le numéro deux, SABMiller. Prix final : environ 79 milliards de livres (plus de 100 milliards de dollars), l'un des cinq plus gros deals de l'histoire. L'ensemble brasserait une bière sur trois vendue dans le monde.",
"Un tel monstre ne passe aucun régulateur sans amputations. Le deal est conditionné à des remèdes (remedies) massifs et pré-négociés : vente de la participation de SABMiller dans MillerCoors aux États-Unis (12 Md$ à Molson Coors), cession des marques européennes Peroni, Grolsch et Pilsner Urquell à Asahi, et cession de la participation dans le chinois CR Snow. AB InBev vend par avance tout ce qui créerait un chevauchement inacceptable — c'est le prix du feu vert dans une trentaine de juridictions.",
"Autre subtilité : entre l'annonce et le closing, le Brexit fait plonger la livre. Le prix étant en livres, certains actionnaires réclament et obtiennent une rallonge. Le deal close en octobre 2016. La suite est moins glorieuse : AB InBev se retrouve avec plus de 100 milliards de dette au moment où la consommation de bière stagne et où la craft beer grignote les parts. Le titre mettra des années à s'en remettre. Même un monopole quasi mondial ne protège pas d'un bilan trop lourd."
],
questions:[
{q:"Que sont les « remedies » dans un contrôle des concentrations ?", opts:["Des amendes payées au régulateur","Des engagements — souvent des cessions d'actifs — proposés pour éliminer les chevauchements concurrentiels et obtenir l'autorisation du deal","Des indemnités versées aux concurrents","Des baisses de prix promises aux consommateurs"], a:1, exp:"Plutôt que d'interdire une fusion, les autorités (Commission européenne, DOJ/FTC…) acceptent des remèdes : céder les activités qui créeraient une position dominante sur un marché donné. Les céder à un repreneur crédible, et souvent avant le closing (fix-it-first)."},
{q:"Pourquoi un deal mondial doit-il être notifié dans des dizaines de juridictions ?", opts:["Par courtoisie diplomatique","Chaque autorité de concurrence est compétente dès que le deal dépasse ses seuils locaux de chiffre d'affaires : un seul refus majeur (UE, US, Chine) peut tuer l'ensemble","Seule l'UE compte vraiment","Pour optimiser les impôts"], a:1, exp:"Le contrôle des concentrations est territorial : Bruxelles, Washington, Pékin, Pretoria… chacun juge l'effet sur son marché. Le calendrier du deal se cale sur le régulateur le plus lent, et les remèdes s'empilent juridiction par juridiction."},
{q:"Quel risque financier le Brexit a-t-il matérialisé dans ce deal ?", opts:["Le risque de taux","Le risque de change entre annonce et closing : un prix fixé dans une devise qui bouge change la valeur réelle de l'offre pour une partie des actionnaires","Le risque climatique","Le risque de fraude"], a:1, exp:"Des mois séparent l'annonce du closing. Si le prix est en livres et que la livre plonge, les actionnaires payés en autre chose (ou comparant à des offres en dollars) perdent de la valeur. D'où renégociation. Le risque de change d'un deal se couvre (hedging) ou se partage contractuellement."},
{q:"Quelle limite du modèle « consolidation + levier » ce deal illustre-t-il ?", opts:["Aucune, le deal fut un triomphe","La dette d'acquisition suppose des cash-flows croissants ; si le marché sous-jacent stagne ou se fragmente (craft beer), le désendettement étouffe toute stratégie","Les brasseurs sont mal gérés","La bière est un actif risqué pour les banques"], a:1, exp:"Le levier est un accélérateur, pas une stratégie. AB InBev a passé les années suivantes à couper le dividende et vendre des actifs pour désendetter, pendant que le marché bougeait. La consolidation atteint sa limite quand il n'y a plus de croissance à acheter."}
],
lesson:"Sur un mégadeal, l'antitrust se prépare avant la signature : remèdes pré-vendus, calendrier réaliste, et risque de change couvert. Et la dette se calibre sur le marché de demain, pas d'hier."
},
{
id:"suezveolia", title:"Veolia – Suez : l'OPA hostile à la française", tag:"OPA hostile", year:"2020-2021", place:"France",
story:[
"Août 2020 : Veolia annonce vouloir racheter à Engie sa participation de 29,9 % dans Suez, son rival historique dans l'eau et les déchets, prélude à une OPA sur le reste. Pourquoi 29,9 % ? Parce qu'en France, franchir 30 % du capital déclenche l'obligation de déposer une offre publique sur 100 % des titres. Veolia se poste juste sous le seuil, le temps de préparer la suite.",
"Suez ne se laisse pas faire et sort une défense spectaculaire : le conseil loge l'activité Eau France dans une fondation de droit néerlandais (stichting), rendant cet actif stratégique incessible pendant quatre ans sans accord du conseil — une pilule empoisonnée à l'européenne, destinée à rendre la proie indigestible. S'ensuivent des mois de guerre totale : procédures devant toutes les juridictions, campagnes de presse, interventions du gouvernement qui appelle au « ni hostile ni amical, patriotique ».",
"Le blocage juridique fonctionne assez pour forcer la table des négociations. Avril 2021 : accord à 20,50 € par action (contre 18 € initialement, environ 13 milliards d'euros au total), avec un démantèlement négocié — un « nouveau Suez » (les actifs France, environ 7 milliards de chiffre d'affaires) est revendu à un consortium de fonds (Meridiam, GIP, Caisse des Dépôts) pour préserver la concurrence et l'emploi, Veolia gardant l'international. La stichting est dissoute. Leçon : une défense anti-OPA ne sert presque jamais à rester indépendant — elle sert à faire monter le prix et à négocier les conditions de la reddition."
],
questions:[
{q:"Pourquoi le seuil de 30 % est-il si important en droit boursier français ?", opts:["C'est le seuil de la minorité de blocage","Au-delà de 30 % du capital ou des droits de vote, le dépôt d'une offre publique obligatoire sur la totalité des titres s'impose","Il déclenche une nationalisation","Il oblige à publier les comptes"], a:1, exp:"L'offre publique obligatoire (article 234-2 RG AMF) protège les minoritaires : celui qui prend le contrôle de fait doit offrir à tous une porte de sortie au même prix. D'où les prises de participation calibrées à 29,9 % — juste sous la ligne."},
{q:"Quel était le mécanisme de la défense « stichting » de Suez ?", opts:["Une augmentation de capital dilutive","Loger un actif stratégique dans une fondation néerlandaise le rendant incessible plusieurs années, pour priver l'assaillant de ce qu'il convoite et le forcer à négocier","Un rachat d'actions massif","Une fusion défensive avec un tiers"], a:1, exp:"La stichting néerlandaise permet de sanctuariser un actif hors de portée de l'acquéreur. But réel : pas l'indépendance éternelle, mais du levier de négociation — rendre l'OPA moins attractive tant que le conseil n'a pas obtenu prix et garanties."},
{q:"Que doit faire le conseil d'administration d'une cible d'OPA hostile, juridiquement ?", opts:["Défendre l'emploi à tout prix","Agir dans l'intérêt social de la société, en appréciant l'offre (prix, projet) — il rend un avis motivé, éclairé par une expertise indépendante","Obéir au gouvernement","Refuser toute discussion"], a:1, exp:"En France, le conseil d'une cible émet un avis motivé sur l'offre, appuyé sur une attestation d'équité d'un expert indépendant. Il peut mettre en place des défenses (dans les limites de ses pouvoirs et de l'AG), mais toujours au nom de l'intérêt social, pas de l'auto-préservation des dirigeants."},
{q:"Pourquoi la revente du « nouveau Suez » à un consortium faisait-elle partie du deal ?", opts:["Pour payer moins d'impôts","Antitrust et politique : Veolia + Suez France aurait créé un quasi-monopole de l'eau en France ; céder les actifs domestiques désamorçait le veto concurrentiel et l'opposition du gouvernement","Parce que ces actifs perdaient de l'argent","Pour rembourser la dette de Suez"], a:1, exp:"Comme les remedies d'AB InBev : céder le chevauchement domestique achetait à la fois le feu vert de la concurrence et la paix politique (emploi, service public de l'eau). Le périmètre final d'un deal hostile est presque toujours co-écrit par le régulateur."}
],
lesson:"Les défenses anti-OPA (seuils, stichting, pilules) ne sauvent pas l'indépendance : elles achètent du temps et du prix. Connaître les seuils réglementaires (30 % en France) est non négociable."
},
{
id:"lehman", title:"Lehman Brothers — le week-end où tout a cassé", tag:"Faillite systémique", year:"2008", place:"États-Unis",
story:[
"Septembre 2008. Lehman Brothers, banque d'investissement de 158 ans, quatrième de Wall Street, est gorgée d'actifs immobiliers toxiques (subprimes, immobilier commercial) financés avec un levier délirant : plus de 30 fois ses fonds propres, et une dépendance mortelle au financement au jour le jour (repo). Pour enjoliver ses ratios trimestriels, la banque utilisait « Repo 105 » : une astuce comptable classant des opérations de pension comme des ventes, faisant disparaître temporairement 50 milliards de dollars du bilan à chaque publication.",
"Quand la confiance s'évapore, le financement court terme aussi : les contreparties exigent plus de collatéral, les hedge funds retirent leurs actifs, les prêteurs repo se retirent. Le week-end du 13-14 septembre, le Trésor et la Fed convoquent Wall Street pour organiser un sauvetage privé. Bank of America préfère racheter Merrill Lynch. Barclays veut bien reprendre Lehman, mais le régulateur britannique refuse de garantir les engagements pendant le week-end. Aucun acheteur, pas de garantie publique : lundi 15 septembre à 1h45, Lehman dépose le bilan — 639 milliards de dollars d'actifs, la plus grosse faillite de l'histoire.",
"L'onde de choc est planétaire : fonds monétaires qui « cassent le dollar », marché interbancaire gelé, AIG sauvée in extremis le surlendemain, plans de sauvetage de centaines de milliards. La leçon structurelle : le levier détermine la taille de la chute, mais c'est la structure de financement qui détermine la vitesse. Financer des actifs illiquides à 30 ans avec de la dette au jour le jour, c'est construire sur un pont qui peut disparaître en une nuit."
],
questions:[
{q:"Qu'est-ce qui rendait le bilan de Lehman si fragile, au-delà du levier ?", opts:["Trop de trésorerie dormante","L'asymétrie de maturité : des actifs illiquides de long terme financés par de la dette au jour le jour (repo), qui peut se retirer en 24 heures","Trop de fonds propres","Une exposition aux devises émergentes"], a:1, exp:"Le levier ×30 dit combien on tombe ; le financement court terme dit à quelle vitesse. Quand les prêteurs repo se retirent, il faut vendre les actifs illiquides en urgence, à prix bradés — la spirale mortelle (fire sale) commence."},
{q:"Qu'était le « Repo 105 » ?", opts:["Un produit dérivé de taux","Une astuce comptable classant des opérations de pension comme des ventes fermes, pour sortir ~50 Md$ du bilan juste avant chaque publication trimestrielle","Un plan de sauvetage de la Fed","Un ratio réglementaire"], a:1, exp:"En livrant du collatéral valant 105 pour recevoir 100 de cash, Lehman obtenait un traitement de « vente » et non d'emprunt garanti. Le bilan publié paraissait moins leveragé qu'en réalité. Le window dressing des ratios est un signal de détresse, pas de santé."},
{q:"Pourquoi le rachat par Barclays a-t-il échoué au dernier moment ?", opts:["Le prix était trop élevé","Le régulateur britannique (FSA) a refusé d'autoriser Barclays à garantir les engagements de Lehman sans vote des actionnaires — impossible en un week-end","Lehman a refusé l'offre","La Fed a interdit la vente"], a:1, exp:"Une garantie des engagements d'une banque en perdition = risque massif pour l'acheteur ; la règle britannique exigeait l'accord des actionnaires. Sans garantie pendant l'interrègne, pas de deal possible. Un closing peut mourir sur un détail réglementaire de procédure."},
{q:"Quelle notion Lehman a-t-elle gravée dans la régulation bancaire mondiale ?", opts:["Le secret bancaire","Le risque systémique : la faillite d'un acteur interconnecté propage des pertes en cascade — d'où Bâle III, les ratios de liquidité (LCR/NSFR) et le statut d'établissement systémique","La titrisation est interdite","Les banques ne peuvent plus faire faillite"], a:1, exp:"Après Lehman : exigences de fonds propres renforcées, ratios de liquidité imposant de survivre 30 jours de stress (LCR), surcharges pour les banques systémiques (G-SIB), mécanismes de résolution. Toute la régulation post-2008 est une réponse à ce week-end."}
],
lesson:"Le levier fixe l'ampleur de la chute, la structure de financement en fixe la vitesse. Actifs illiquides + dette au jour le jour = mort subite possible, quels que soient les profits affichés."
},
{
id:"casino", title:"Casino / Rallye — la pyramide de holdings", tag:"Restructuration", year:"2018-2024", place:"France",
story:[
"Jean-Charles Naouri contrôle le distributeur Casino (Monoprix, Franprix, Géant) à travers une cascade de holdings : Rallye au-dessus de Casino, Foncière Euris au-dessus de Rallye, Finatis puis Euris au sommet. Chaque étage porte sa propre dette, gagée sur les actions de l'étage du dessous, et vit des dividendes qui remontent. Le montage permet de contrôler un groupe de 30 milliards de chiffre d'affaires avec une mise personnelle limitée : c'est le levier par empilement.",
"La mécanique a une condition de survie : que le cours de Casino tienne et que les dividendes coulent. Or Casino, très endetté lui-même et attaqué par des vendeurs à découvert (dont Muddy Waters dès 2015, qui dénonce précisément l'opacité du montage), voit son cours glisser. Les banques de Rallye, dont les prêts sont gagés sur des actions Casino qui valent de moins en moins, exigent du collatéral. Pour payer ses dividendes, Casino vend ses murs de magasins et ses meilleurs actifs — on brûle les meubles pour chauffer la maison. Mai 2019 : Rallye et ses holdings se placent en procédure de sauvegarde, gelant 3 milliards d'euros de dette.",
"La suite est une lente agonie : plans de sauvegarde, cessions en série, puis restructuration finale de Casino lui-même en 2023-2024 — conciliation, dette convertie en capital, arrivée du trio Kretinsky/Ladreit de Lacharrière/Attestor, actionnaires historiques quasi anéantis, Naouri évincé. Moralité : une pyramide de holdings endettées est une vente à découvert inversée sur ta propre entreprise — tout va bien tant que ça monte, et tout s'effondre ensemble quand ça baisse."
],
questions:[
{q:"Quel est le principe (et le danger) d'une cascade de holdings endettées ?", opts:["Optimiser la TVA","Contrôler un groupe avec peu de capital en empilant des dettes gagées sur les titres de l'étage inférieur — mais la baisse du cours de la base propage un appel de collatéral à tous les étages","Éviter les OPA hostiles","Mutualiser les équipes"], a:1, exp:"Chaque holding emprunte contre les actions du dessous. Si le cours de la base chute, la valeur du gage fond à chaque étage simultanément : appels de marge, ventes forcées, spirale. Le levier d'empilement démultiplie la hausse ET la baisse."},
{q:"Qu'est-ce qu'une procédure de sauvegarde en droit français ?", opts:["Une faillite avec liquidation immédiate","Une procédure préventive : l'entreprise qui n'est pas encore en cessation des paiements obtient le gel de ses dettes et négocie un plan sous protection du tribunal","Un rachat par l'État","Un simple rééchelonnement amiable"], a:1, exp:"La sauvegarde (inspirée du Chapter 11 américain) permet de geler le passif AVANT la cessation des paiements. Rallye y a gelé 3 Md€ de dette. Outil puissant : le débiteur reste aux commandes et impose du temps à ses créanciers."},
{q:"Pourquoi la politique de dividende de Casino était-elle un signal d'alarme ?", opts:["Les dividendes étaient trop faibles","Casino versait des dividendes élevés non couverts par ses cash-flows, financés par cessions d'actifs, parce que les holdings au-dessus en avaient besoin pour servir leur propre dette","Les dividendes étaient versés en actions","Ils étaient versés deux fois par an"], a:1, exp:"Quand la politique de distribution sert les besoins de l'actionnaire de contrôle plutôt que la logique de l'entreprise, la gouvernance est captive. Un dividende financé par la vente des meilleurs actifs appauvrit structurellement l'entreprise — red flag majeur."},
{q:"Que devient la dette dans la restructuration finale de Casino (2023-24) ?", opts:["Elle est remboursée intégralement","Une large part est convertie en capital (debt-to-equity swap) : les créanciers deviennent actionnaires et les actionnaires historiques sont dilués à presque zéro","Elle est annulée sans contrepartie","L'État la reprend"], a:1, exp:"Quand la dette dépasse la valeur d'entreprise, les créanciers sont les vrais propriétaires économiques. Le debt-equity swap acte cette réalité : la valeur se réalloue selon l'ordre de priorité (waterfall), et l'equity, dernier servi, est essuyé."}
],
lesson:"Regarde toujours qui contrôle l'entreprise et avec quelle dette. Une pyramide de holdings transforme une baisse de cours en crise existentielle, et une politique de dividende peut révéler une gouvernance captive."
},
{
id:"enron", title:"Enron — la machine à profits fictifs", tag:"Fraude comptable", year:"2001", place:"États-Unis",
story:[
"Enron, ex-gazier texan devenu trader d'énergie, est la coqueluche de Wall Street : « entreprise la plus innovante d'Amérique » six années de suite selon Fortune, 7e capitalisation américaine. Son arme comptable : le mark-to-market appliqué à des contrats d'énergie de 20 ans — Enron comptabilise AUJOURD'HUI la totalité des profits futurs estimés d'un contrat signé, sur la base de ses propres modèles. Signer un contrat = fabriquer du profit immédiat. Encore faut-il en signer toujours plus, et que le cash, lui, n'arrive jamais aussi vite que le résultat.",
"Pour cacher la dette et les actifs pourris, le CFO Andrew Fastow construit des centaines de véhicules hors-bilan (SPE — special purpose entities) aux noms de films : LJM, Raptors, Chewco. Ces entités « indépendantes » rachètent les mauvais actifs d'Enron à bon prix… en étant garanties par des actions Enron. Tant que le titre monte, la pyramide tient. Fastow se rémunère personnellement au passage — conflit d'intérêts approuvé par le conseil, avec l'aval des avocats et de l'auditeur Arthur Andersen, qui touche autant en conseil qu'en audit.",
"Été 2001 : le titre glisse, les garanties en actions se déclenchent, la pyramide s'effondre sur elle-même. Restatement des comptes, confiance anéantie, faillite en décembre 2001 — la plus grosse de l'histoire à l'époque. Andersen, condamné pour avoir broyé des tonnes de documents, disparaît : 85 000 salariés, un des Big Five rayé de la carte. Le Congrès vote Sarbanes-Oxley en 2002 : certification personnelle des comptes par CEO et CFO, sous peine de prison. L'héritage d'Enron tient en une règle : quand le résultat croît sans que le cash suive, année après année, ce n'est pas de l'avance — c'est de la fiction."
],
questions:[
{q:"Quel était le vice fondamental du mark-to-market façon Enron ?", opts:["Le mark-to-market est illégal","Comptabiliser immédiatement des profits futurs estimés par ses propres modèles, invérifiables et jamais confirmés par du cash","Il sous-évaluait les profits","Il ne s'appliquait qu'aux dérivés"], a:1, exp:"Le mark-to-market est légitime sur des actifs liquides à prix observable. Sur des contrats de 20 ans valorisés par les modèles internes du vendeur, c'est une machine à imprimer du résultat : l'estimation EST le profit, et personne ne peut la contester avant des années."},
{q:"À quoi servaient les SPE de Fastow ?", opts:["À optimiser la TVA","À sortir dettes et actifs toxiques du bilan consolidé, en les « vendant » à des entités garanties… par des actions Enron elles-mêmes","À payer les salariés en actions","À financer la R&D"], a:1, exp:"Le hors-bilan cachait le levier réel. Le vice circulaire : les SPE étaient adossées au titre Enron — la protection disparaissait exactement quand on en avait besoin (titre en baisse). Toute structure dont la solidité dépend du cours de son sponsor est une bombe à retardement."},
{q:"Pourquoi les « gardiens » (auditeur, avocats, analystes, agences) ont-ils tous failli ?", opts:["Ils étaient incompétents","Conflits d'intérêts structurels : Andersen touchait des honoraires de conseil massifs, les analystes travaillaient pour des banques qui vendaient des services à Enron — le gardien payé par le surveillé finit par regarder ailleurs","La loi les en empêchait","Enron était trop complexe pour être audité"], a:1, exp:"La leçon systémique : l'indépendance des gatekeepers est une fiction quand leurs revenus dépendent du client contrôlé. D'où SOX : rotation, séparation audit/conseil, comités d'audit indépendants. En analyse, ne sous-traite jamais ton scepticisme à un tiers payé par la cible."},
{q:"Qu'a changé Sarbanes-Oxley (2002) pour un CFO ?", opts:["Rien, c'est une loi boursière","Certification personnelle des comptes sous peine de sanctions pénales : le CFO engage sa liberté, pas seulement sa réputation, sur la sincérité des états financiers","L'interdiction du mark-to-market","La nationalisation de l'audit"], a:1, exp:"Sections 302/906 : CEO et CFO certifient personnellement. « Je ne savais pas » n'est plus une défense — le contrôle interne (SOX 404) doit être documenté et testé. C'est la réponse directe au « je faisais confiance à mes équipes » des dirigeants d'Enron."}
],
lesson:"Résultat qui monte + cash qui ne suit pas + structures que personne ne comprend + gardiens grassement payés = sors. Aucune exception connue."
},
{
id:"wework", title:"WeWork — 47 milliards de storytelling", tag:"Gouvernance / IPO", year:"2019", place:"États-Unis",
story:[
"Adam Neumann, gourou charismatique de 2 mètres, a convaincu SoftBank et son fonds Vision que WeWork — une société qui loue des bureaux longue durée pour les sous-louer courte durée — n'est pas de l'immobilier mais une « tech company » qui va « élever la conscience du monde ». Dernière valorisation privée : 47 milliards de dollars, fixée essentiellement par un seul investisseur enthousiaste, SoftBank, qui remet au pot à chaque tour.",
"Août 2019 : WeWork publie son prospectus d'introduction en bourse (S-1). Pour la première fois, le marché entier peut lire les chiffres — et il découvre l'envers du décor : 1,9 milliard de pertes annuelles, un modèle structurellement risqué (engagements de loyers de 47 milliards sur 15 ans contre des clients qui peuvent partir au mois — l'asymétrie de duration d'une banque, sans la régulation), et une gouvernance ahurissante : actions à droits de vote 20:1 pour Neumann, immeubles personnels loués à WeWork, marque « We » rachetée 5,9 millions… à Neumann lui-même, et une succession prévoyant que sa femme choisirait le prochain CEO.",
"En six semaines, la valorisation évoquée passe de 47 à moins de 15 milliards, l'IPO est retirée, Neumann est débarqué — avec un parachute qui fera scandale — et SoftBank doit sauver la société à une valorisation d'environ 8 milliards pour protéger sa mise. La leçon vaut de l'or : une valorisation privée n'est pas un prix de marché, c'est le prix qu'UN acheteur motivé a accepté de payer au dernier tour. Le S-1 n'a rien révélé de caché — tout était connu des initiés. C'est la confrontation au scepticisme public qui a fait fondre 40 milliards de « valeur »."
],
questions:[
{q:"Pourquoi une valorisation privée de 47 Md$ a-t-elle pu s'évaporer si vite ?", opts:["Fraude comptable","Elle reposait sur le prix payé par un seul investisseur motivé au dernier tour, pas sur une confrontation large d'acheteurs et de vendeurs : l'IPO a soumis le prix au marché, qui a refusé","Les taux ont monté brutalement","Un concurrent a cassé les prix"], a:1, exp:"Une valo de tour privé = un prix négocié bilatéralement, souvent avec des protections (liquidation preferences) qui en réduisent le sens économique. Ne compare jamais une valo privée à une capitalisation boursière sans lire les termes du tour."},
{q:"Quel était le risque structurel du modèle WeWork ?", opts:["Le télétravail","L'asymétrie d'engagements : loyers fermes de 15 ans au passif, clients résiliables au mois à l'actif — la structure de risque d'une banque (emprunter court, prêter long, en miroir), sans le régulateur","Le prix du café","La dépendance à un fournisseur"], a:1, exp:"En cycle haut, l'écart de loyer est une marge. En récession, les clients partent en 30 jours et les loyers restent 15 ans. La transformation de maturité est le cœur du risque — la même mécanique que Lehman ou SVB, version immobilière."},
{q:"Pourquoi les actions à droits de vote multiples (20:1) sont-elles un red flag ?", opts:["Elles sont illégales en Europe","Elles déconnectent pouvoir et capital : le dirigeant contrôle tout en possédant une fraction, et plus personne — board, actionnaires — ne peut le sanctionner ou le remplacer","Elles coûtent plus cher fiscalement","Elles empêchent l'IPO"], a:1, exp:"Le contrôle sans contre-pouvoir transforme les conflits d'intérêts en système (immeubles personnels, marque « We »...). Question systématique de gouvernance : « qui peut dire non au patron, et que lui en coûte-t-il ? » Si la réponse est « personne », le risque n'est pas dans les comptes, il est dans la structure."},
{q:"Que nous apprend le processus d'IPO dans cette histoire ?", opts:["L'IPO est un moyen de financement dépassé","Le prospectus et la confrontation au marché sont une due diligence publique : des faits connus des initiés mais jamais challengés ne survivent pas à l'examen collectif","Il faut coter plus vite pour éviter les fuites","Les banques fixent mal les prix"], a:1, exp:"Tout était dans le S-1 — pertes, conflits, gouvernance. Les investisseurs privés les avaient acceptés dans l'euphorie. La leçon d'analyste : l'information ne suffit pas, c'est le scepticisme organisé qui fait les prix. Sois celui qui lit le prospectus comme si personne d'autre ne l'avait fait."}
],
lesson:"Une valorisation privée est une opinion d'initié ; un prix de marché est un verdict. Et la gouvernance n'est pas un sujet « soft » : c'est elle qui décide si les problèmes peuvent être corrigés avant qu'ils coûtent 40 milliards."
},
{
id:"archegos", title:"Archegos — le levier que personne ne voyait", tag:"Levier / Dérivés", year:"2021", place:"États-Unis",
story:[
"Bill Hwang gère Archegos, un family office — donc quasiment aucune obligation déclarative. Sa stratégie : des positions colossales et concentrées sur une poignée d'actions (ViacomCBS, Discovery, quelques tech chinoises), construites non pas en achetant les titres, mais via des total return swaps (TRS) avec les plus grandes banques : la banque détient l'action, Archegos touche (ou paie) la performance. Résultat : une exposition économique de plus de 100 milliards de dollars avec ~10 milliards de fonds propres — et aucune déclaration publique, puisque juridiquement, Archegos ne « possède » rien.",
"Le détail mortel : Hwang a répliqué le même montage chez six, sept banques à la fois — Goldman Sachs, Morgan Stanley, Credit Suisse, Nomura, UBS... Chacune voyait sa propre tranche, aucune ne voyait le total. Chacune croyait financer une position raisonnable ; ensemble, elles finançaient une bombe : sur certains titres, Archegos contrôlait économiquement plus de 10 % du flottant, et sa propre pression acheteuse faisait monter les cours qui validaient ses appels de marge.",
"Mars 2021 : ViacomCBS annonce une augmentation de capital, le titre décroche, les appels de marge pleuvent. Les banques convoquent une réunion de crise et évoquent une liquidation ordonnée — puis Goldman et Morgan Stanley vendent en premier, en blocs massifs, pendant que les autres « coopèrent ». Credit Suisse, plus lent et plus exposé, perd 5,5 milliards de dollars ; Nomura 2,9. Archegos vaut zéro en 48 heures. Triple leçon : le levier par dérivés est invisible dans les déclarations classiques ; le risque de contrepartie se mesure sur l'exposition TOTALE du client, pas sur ta tranche ; et dans une liquidation, la coopération est un dilemme du prisonnier — le premier qui vend s'en sort."
],
questions:[
{q:"Comment un TRS (total return swap) permet-il un levier invisible ?", opts:["Il est comptabilisé deux fois","Il donne l'exposition économique d'une action sans la détenir juridiquement : pas de franchissement de seuil à déclarer, et chaque banque contrepartie ne voit que sa propre part","Il supprime le risque de perte","Il est garanti par l'État"], a:1, exp:"Le swap sépare la propriété juridique (la banque) de l'exposition économique (le client). Les seuils déclaratifs classiques visaient la propriété — Archegos a montré le trou. Depuis, régulateurs et prime brokers exigent davantage de transparence sur l'exposition agrégée."},
{q:"Pourquoi aucune banque n'a-t-elle vu le danger ?", opts:["Elles n'avaient pas les données de leur propre exposition","Asymétrie structurelle : chacune connaissait SA tranche et ignorait que le même montage existait chez cinq concurrentes — le levier total n'existait dans aucun système","Hwang falsifiait ses comptes","Le régulateur le leur cachait"], a:1, exp:"Chaque risk manager voyait un client concentré mais « gérable ». Le risque était dans l'agrégat, invisible par construction. Leçon générale de crédit : demande toujours l'endettement TOTAL de ta contrepartie, tous prêteurs confondus — et méfie-toi si elle refuse de répondre."},
{q:"Que déclenche mécaniquement la chute du cours dans ce montage ?", opts:["Une baisse des impôts","Des appels de marge : le collatéral ne couvre plus l'exposition, il faut remettre du cash immédiatement ou être liquidé — et la liquidation fait baisser le cours, qui aggrave les appels de marge","La suspension du titre","Un rachat automatique par la banque"], a:1, exp:"C'est la spirale du levier : marge → vente forcée → baisse → marge. Identique à Rallye/Casino (titres nantis) et aux LBO en crise. Le levier ne crée pas le risque de baisse, il en fait une réaction en chaîne à vitesse exponentielle."},
{q:"Quelle leçon de théorie des jeux la liquidation d'Archegos illustre-t-elle ?", opts:["La coopération l'emporte toujours","Le dilemme du prisonnier : l'accord collectif de liquidation ordonnée maximise la valeur commune, mais le premier qui trahit et vend sauve sa mise — Goldman a vendu, Credit Suisse a payé","Les marchés sont efficients","Il ne faut jamais vendre en bloc"], a:1, exp:"Quand la valeur fond, l'incitation individuelle à défausser en premier écrase toute promesse de coordination. En pratique : dans toute situation de détresse partagée (syndicat bancaire, actionnaires d'une boîte en crise), anticipe que les autres défendront leur intérêt, pas l'accord."}
],
lesson:"Le levier le plus dangereux est celui qui n'apparaît dans aucun document. Mesure l'exposition économique totale, jamais la propriété juridique — et en cas de fire sale, la sortie appartient aux rapides."
},
{
id:"svb", title:"Silicon Valley Bank — morte en 48 heures", tag:"Risque de taux / ALM", year:"2023", place:"États-Unis",
story:[
"SVB est LA banque de la tech californienne : entre 2020 et 2021, l'argent du boom du capital-risque fait tripler ses dépôts, à près de 190 milliards de dollars. Problème de riche : que faire de tout ce cash ? La banque l'investit massivement en obligations d'État et créances hypothécaires de LONGUE durée, achetées au sommet du marché obligataire, quand les taux étaient quasi nuls. Comptablement, l'essentiel est classé en « held-to-maturity » (HTM) : tant qu'on garde les titres jusqu'à l'échéance, les variations de valeur n'apparaissent pas au bilan.",
"2022 : la Fed remonte ses taux à la vitesse la plus brutale depuis 40 ans. Mécanique implacable : quand les taux montent, les obligations existantes à taux faibles perdent de la valeur — et plus leur duration est longue, plus la chute est violente. Les pertes latentes de SVB dépassent 15 milliards de dollars, soit environ la totalité de ses fonds propres. La banque est économiquement insolvable, mais la comptabilité HTM rend la chose invisible — tant que personne n'oblige à vendre.",
"Mars 2023 : pour faire face aux retraits (la tech brûle du cash, les dépôts fondent), SVB vend son portefeuille disponible à la vente en encaissant 1,8 milliard de pertes, et annonce dans la foulée une augmentation de capital. Le signal est catastrophique. En quelques heures, les fonds de VC disent à toutes leurs participations de retirer leurs fonds — 94 % des dépôts dépassaient le plafond de garantie fédérale, et tout le monde se connaît dans la Valley. 42 milliards de dollars sortent en UNE journée, par app mobile. Le lendemain matin, le régulateur ferme la banque. Une panique bancaire prenait des semaines en 1930 ; à l'ère de Twitter et du mobile banking, elle prend un après-midi."
],
questions:[
{q:"Pourquoi la hausse des taux détruit-elle la valeur des obligations existantes ?", opts:["Les émetteurs font défaut","Une obligation à 1 % ne trouve preneur face aux nouvelles à 4 % qu'avec une décote : le prix baisse pour égaliser les rendements, et d'autant plus que la maturité (duration) est longue","L'inflation ronge le nominal","Les banques centrales les rachètent"], a:1, exp:"Relation inverse prix/taux, amplifiée par la duration : ~1 % de perte par point de duration pour 1 % de hausse de taux. Un portefeuille de duration 6 perd ~24 % si les taux montent de 4 points. SVB avait fait un pari directionnel massif sur les taux sans le dire (ni peut-être le voir)."},
{q:"Quel rôle a joué la comptabilité held-to-maturity (HTM) ?", opts:["Elle a créé les pertes","Elle les a masquées : les titres HTM restent au coût historique tant qu'on ne les vend pas — la perte économique existait, mais n'apparaissait ni au résultat ni dans les ratios","Elle est interdite aux banques","Elle a protégé les déposants"], a:1, exp:"Le HTM repose sur une promesse : « je garderai jusqu'à l'échéance ». Elle ne tient que si la liquidité le permet. Dès qu'il faut vendre, la fiction s'effondre d'un coup. Une convention comptable ne supprime jamais un risque économique — elle en diffère la reconnaissance."},
{q:"Pourquoi la concentration des déposants était-elle aussi dangereuse que le portefeuille obligataire ?", opts:["Les déposants tech sont exigeants","Des milliers de clients du même secteur, non assurés à 94 %, connectés entre eux et conseillés par les mêmes fonds de VC : ils réagissent comme UN SEUL déposant géant","Ils avaient des taux privilégiés","Ils étaient à l'étranger"], a:1, exp:"La stabilité d'une base de dépôts vient de sa diversité. Chez SVB, l'information (et la panique) circulait dans un même réseau social et professionnel. Le passif s'est comporté comme un bloc — l'exact opposé de l'hypothèse statistique qui fonde la banque."},
{q:"Quelle erreur de séquencement la direction a-t-elle commise en mars 2023 ?", opts:["Vendre trop tard dans la semaine","Annoncer la perte de 1,8 Md$ AVANT d'avoir sécurisé l'augmentation de capital : le trou était public, la solution ne l'était pas — le vide a été rempli par la panique","Ne pas prévenir Twitter","Fermer les guichets trop tôt"], a:1, exp:"Règle de communication de crise financière : on annonce le problème et sa solution DANS LE MÊME communiqué, financement bouclé (underwritten). Révéler une plaie sans le pansement invite chacun à courir — rationnellement — vers la sortie."}
],
lesson:"L'actif le plus sûr du monde (des bons du Trésor) peut tuer une banque si la duration est mauvaise. Gère l'actif ET le passif ensemble — et n'annonce jamais un trou sans sa solution financée."
},
{
id:"csubs", title:"Credit Suisse – UBS : le mariage forcé d'un week-end", tag:"Rescue merger", year:"2023", place:"Suisse",
story:[
"Credit Suisse, 167 ans, pilier de la finance suisse, arrive en mars 2023 essoré par une décennie de scandales : Archegos (5,5 Md$), Greensill, espionnage interne, changements de direction en série. La banque est solvable sur le papier — ses ratios réglementaires sont corrects — mais la confiance, elle, est morte : les clients fortunés retirent des dizaines de milliards par trimestre. Quand SVB s'effondre et que le principal actionnaire saoudien déclare maladroitement qu'il n'investira « absolument pas » un franc de plus, la panique s'installe. Une banque de gestion de fortune sans confiance est un coffre-fort percé.",
"Le week-end du 18-19 mars, les autorités suisses (gouvernement, BNS, FINMA) orchestrent un sauvetage avant l'ouverture des marchés asiatiques : UBS rachète Credit Suisse pour 3 milliards de francs en actions — moins de 7 % de sa valeur comptable — avec des garanties publiques massives et des lignes de liquidité de la banque centrale. Détail brutal : le gouvernement utilise le droit d'urgence pour passer OUTRE le vote des actionnaires des deux banques. En un week-end, la Suisse marie ses deux géants et crée un monstre de 5 000 milliards d'actifs gérés.",
"Le coup de tonnerre est ailleurs : la FINMA ordonne l'annihilation TOTALE des obligations AT1 de Credit Suisse — 16 milliards de francs réduits à zéro — alors que les actionnaires, théoriquement derniers dans la hiérarchie, reçoivent 3 milliards. Les porteurs d'AT1 hurlent à l'inversion de la hiérarchie des créanciers. Mais le prospectus des AT1 suisses le permettait noir sur blanc : dépréciation intégrale en cas d'« événement de viabilité » déclaré par le régulateur, sans que l'equity soit nécessairement à zéro. Des investisseurs professionnels par milliers découvrent ce week-end-là ce qu'ils avaient signé. La leçon tient en cinq mots : lis les documents avant la crise."
],
questions:[
{q:"Qu'est-ce qu'une obligation AT1 (CoCo) ?", opts:["Une obligation d'État suisse","Un titre hybride bancaire conçu pour absorber les pertes : converti en actions ou déprécié (parfois à zéro) quand la banque atteint un seuil de non-viabilité — d'où son rendement élevé","Une action préférentielle garantie","Un dérivé de taux"], a:1, exp:"Créés après 2008 pour que les créanciers — pas les contribuables — absorbent les pertes bancaires. Le rendement élevé (8-10 %) paie exactement ce risque : l'anéantissement en cas de crise. Beaucoup de porteurs encaissaient le coupon en oubliant la contrepartie."},
{q:"L'inversion apparente de la hiérarchie (AT1 à zéro, actionnaires payés) était-elle une spoliation ?", opts:["Oui, la hiérarchie des créanciers est absolue","Juridiquement non : le prospectus des AT1 suisses prévoyait explicitement la dépréciation totale sur décision du régulateur, indépendamment du sort de l'equity — le risque était contractuel, pas volé","Oui, et les porteurs ont tous été remboursés depuis","Non, car les actionnaires n'ont rien reçu"], a:1, exp:"La hiérarchie « classique » vaut en liquidation. Ici, clause contractuelle spécifique + droit d'urgence. Moralité d'investisseur : la protection vient du document signé, pas du rang théorique. Les AT1 européens (mécanismes différents) se sont d'ailleurs empressés de rassurer leurs marchés."},
{q:"Pourquoi ces sauvetages se jouent-ils toujours en un week-end ?", opts:["Les banquiers sont indisponibles en semaine","Parce qu'il faut une solution annoncée avant l'ouverture des marchés : une banque en perdition qui ouvre lundi sans plan subit une ruée immédiate — le week-end est la seule fenêtre où le temps s'arrête","Par tradition suisse","Pour éviter les journalistes"], a:1, exp:"Lehman, week-end de septembre 2008 ; CS-UBS, week-end de mars 2023. La fenêtre dimanche soir (avant l'Asie) est la vraie deadline. En crise de confiance, le temps de marché est l'ennemi : toute la négociation se compresse dans 60 heures — au prix d'énormes concessions à celui qui peut signer vite."},
{q:"Pourquoi Credit Suisse est-elle morte alors que ses ratios réglementaires étaient corrects ?", opts:["Les ratios étaient falsifiés","Parce que son actif principal — la confiance des clients fortunés — ne figure dans aucun ratio : en gestion de fortune, les clients qui partent EMPORTENT le business, et aucun capital ne compense un exode","Elle était en fait très rentable","Le franc suisse s'est effondré"], a:1, exp:"La solvabilité mesure le passé du bilan ; la confiance détermine son avenir. Une banque commerciale peut survivre en étant détestée ; un gérant de fortune, jamais. La valeur d'une franchise fondée sur la confiance peut passer de 40 Md à 3 Md sans qu'aucun actif comptable ne bouge."}
],
lesson:"Le rendement élevé d'un titre EST le prix d'un risque écrit quelque part dans le prospectus. Trouve-le avant d'investir — pendant la crise, il sera trop tard pour lire."
},
{
id:"bayer", title:"Bayer – Monsanto : acheter un procès à 63 milliards", tag:"Risque juridique", year:"2016-2018", place:"Allemagne / États-Unis",
story:[
"2016 : Bayer, géant allemand de la pharma et de l'agrochimie, lance l'acquisition de l'américain Monsanto — semences OGM, et surtout le Roundup, herbicide au glyphosate le plus vendu du monde. Prix final en 2018 : 63 milliards de dollars, tout en cash, financés par dette et augmentation de capital. Le CEO Werner Baumann en fait le pari de sa vie : créer le numéro un mondial de l'agriculture. Les risques juridiques du glyphosate sont connus — le CIRC l'a classé « cancérogène probable » dès 2015, des plaintes sont déjà déposées — mais Bayer les juge scientifiquement infondés et financièrement gérables.",
"Août 2018, deux mois après le closing : un jury californien accorde 289 millions de dollars à Dewayne Johnson, jardinier atteint d'un lymphome. Le verdict ouvre les vannes : les plaignants affluent par dizaines de milliers — plus de 100 000 dossiers. Chaque procès perdu alimente les suivants. Bayer provisionne, transige (accord-cadre de ~11 milliards en 2020), reperd, reprovisionne. Le total des provisions et règlements dépassera 16 milliards, sans fin claire : contrairement à une dette, un contentieux de masse n'a ni montant ni échéance connus.",
"Le marché rend son verdict : la capitalisation de Bayer tombe DURABLEMENT en dessous des 63 milliards payés pour le seul Monsanto — l'acquisition a détruit plus que sa propre valeur. Baumann, désavoué par une AG historique dès 2019, finit par partir. Le paiement 100 % cash a aggravé le désastre : les actionnaires de Monsanto sont partis avec l'argent, ceux de Bayer sont restés avec l'intégralité du risque. La leçon est celle que tout comité d'investissement devrait encadrer : un passif juridique de masse ne se « gère » pas, il se PRICE — et quand il est impossible à borner, c'est le prix d'achat, pas l'avocat, qui doit absorber le risque."
],
questions:[
{q:"Pourquoi un contentieux de masse est-il plus dangereux qu'une dette au bilan ?", opts:["Il porte des intérêts plus élevés","Il n'a ni montant ni échéance connus : chaque verdict crée un précédent qui attire de nouveaux plaignants — le passif croît avec le temps au lieu de s'amortir","Il est prioritaire sur la dette senior","Il n'est pas déductible fiscalement"], a:1, exp:"Une dette de 10 Md se rembourse selon un échéancier. Un mass tort est un processus auto-alimenté : publicité des verdicts → nouveaux dossiers → pression à transiger → financement de nouveaux recours. La borne supérieure n'existe pas tant que la source (le produit) est en vente."},
{q:"Bayer connaissait le risque glyphosate avant de signer. Où est la faute d'analyse ?", opts:["Ils ne l'avaient pas identifié en DD","Confondre « risque identifié » et « risque pricé » : le connaître ne suffit pas, il fallait le traduire en réduction de prix, en structure protectrice ou en refus du deal — la conviction scientifique n'est pas une couverture juridique face à des jurys populaires","Le risque n'existait pas en 2016","Un problème de traduction juridique"], a:1, exp:"Bayer avait raison de penser que la science lui donnerait raison — et a quand même perdu des milliards : les jurys américains ne jugent pas la littérature scientifique. Le risque pertinent était processuel (jurys, avocats en class actions, punitive damages), pas scientifique. Price le système judiciaire réel, pas le monde rationnel."},
{q:"En quoi le paiement 100 % cash a-t-il aggravé les choses ?", opts:["Le cash coûte plus cher en intérêts","Il a transféré tout le risque aux seuls actionnaires de Bayer : payés en actions, les actionnaires de Monsanto auraient partagé les pertes du glyphosate — partis avec du cash, ils ont laissé 100 % du fardeau","Le change euro-dollar était défavorable","Cela a retardé le closing"], a:1, exp:"Le mode de paiement est une allocation de risque : le cash dit « je suis certain de la valeur », les actions disent « partageons l'incertitude ». Sur une cible à passif non bornable, payer cash revient à vendre une assurance illimitée au vendeur. Relis AOL (le miroir inverse : payer en papier surévalué)."},
{q:"Quel garde-fou de gouvernance a manqué chez Bayer ?", opts:["Un vote des salariés","Un processus de contradiction réel : un deal « de conviction » porté par un CEO, sur lequel le conseil n'organise ni scénario du pire chiffré ni avis contradictoire indépendant, n'a pas de frein — l'AG 2019 a désavoué le management APRÈS l'irréversible","L'autorisation de la BCE","Un comité d'éthique scientifique"], a:1, exp:"Test à appliquer à tout grand deal : existe-t-il un dossier « pire cas » chiffré par une équipe INDÉPENDANTE de celle qui promeut le deal (red team), et le conseil a-t-il le pouvoir réel de dire non ? Chez Bayer, le pire cas (100k plaintes) n'était dans aucun scénario du board."}
],
lesson:"Un risque identifié mais non pricé est un risque accepté gratuitement. Face à un passif non bornable : réduction de prix massive, structure qui isole, paiement en actions — ou on passe son tour."
}
];
