// LE CLOSING — Drills : cascades comptables, paper LBO, missions terrain, entretien en anglais

// ---- CASCADES COMPTABLES : dérouler P&L → Flux → Bilan, la question d'entretien reine ----
// Même format que les cas : setup / task / grid / coach (grille à cocher)
const CASCADES = [
{id:"k1", title:"L'amortissement augmente de 10", tag:"Le grand classique",
setup:"Question d'entretien la plus posée au monde. Ton entreprise passe 10 M€ d'amortissement supplémentaire cette année. IS à 25 %. Tout le reste est constant.",
task:"Déroule l'impact complet sur les trois états : compte de résultat, tableau de flux, bilan. Chiffre chaque ligne.",
grid:[
"<b>Compte de résultat :</b> EBIT −10 (l'amortissement est une charge opérationnelle). Impôt −2,5 (on paie 25 % de moins sur un résultat plus bas). Résultat net −7,5.",
"<b>Tableau de flux :</b> on part du résultat net (−7,5), on RAJOUTE l'amortissement (+10) car il est non-cash. Flux de trésorerie opérationnel : +2,5. Oui, PLUS de cash — l'économie d'impôt est bien réelle, la charge ne l'est pas.",
"<b>Bilan :</b> actif — immobilisations −10 (amorties), trésorerie +2,5 → total actif −7,5. Passif — capitaux propres −7,5 (via le résultat net). Le bilan équilibre : −7,5 = −7,5. ✓",
"<b>La phrase de synthèse attendue :</b> « une charge non-cash détruit du résultat comptable mais CRÉE du cash via le bouclier fiscal — de +2,5 exactement, soit 10 × le taux d'IS »."
],
coach:"Si tu n'as pas vérifié l'équilibre du bilan à la fin, tu as fait 80 % du travail : l'équilibre EST la preuve. Et retiens la structure de réponse : toujours P&L → Flux → Bilan, dans cet ordre, en chiffrant chaque ligne. C'est un ballet — répète-le jusqu'à le danser."},
{id:"k2", title:"Vente à crédit de 100", tag:"Résultat ≠ cash",
setup:"Tu vends pour 100 M€ de marchandises (qui t'avaient coûté 60, déjà en stock) à un client qui paiera dans 90 jours. IS 25 %, payé cash immédiatement pour simplifier.",
task:"Déroule les trois états au moment de la vente. Où est le paradoxe ?",
grid:[
"<b>Compte de résultat :</b> CA +100, coût des ventes −60 → marge +40. Impôt −10. Résultat net +30. Superbe trimestre.",
"<b>Tableau de flux :</b> résultat net +30, MAIS variation de BFR : créance client +100 (cash non encaissé, à déduire), stock −60 (déjà décaissé avant, à réintégrer). Flux opérationnel : 30 − 100 + 60 = −10. L'entreprise a PERDU du cash sur une vente rentable (l'impôt payé cash, sans encaissement client).",
"<b>Bilan :</b> stocks −60, créances +100, trésorerie −10 → actif +30. Capitaux propres +30 (résultat). Équilibre ✓.",
"<b>Le paradoxe à verbaliser :</b> le profit est là, le cash viendra dans 90 jours — mais l'impôt, lui, se paie tout de suite. Une entreprise en forte croissance de ventes à crédit ENRICHIT son P&L et ASSÈCHE sa trésorerie : c'est l'overtrading, tueur d'entreprises rentables."
],
coach:"L'examinateur pose cette question pour voir si tu confonds résultat et trésorerie. Le mot « BFR » devait apparaître dans ta réponse. S'il n'y était pas, retourne à la leçon sur le BFR et refais ce drill dans trois jours."},
{id:"k3", title:"Provision puis décaissement", tag:"Deux temps",
setup:"Année 1 : tu provisionnes 20 M€ pour un litige (non déductible fiscalement tant que non décaissé). Année 2 : tu perds le procès et paies exactement 20 M€. IS 25 %.",
task:"Déroule les trois états pour CHACUNE des deux années. C'est un exercice en deux temps — la symétrie est le piège.",
grid:[
"<b>Année 1 — P&L :</b> charge de provision −20 → résultat avant impôt −20. MAIS la provision n'est pas déductible : l'impôt ne bouge pas. Résultat net −20 (et naissance d'un impôt différé actif de 5 : tu déduiras plus tard).",
"<b>Année 1 — Flux :</b> résultat net −20, on réintègre la provision non-cash +20 → flux opérationnel 0. Aucun cash n'a bougé. <b>Bilan :</b> provision +20 au passif, capitaux propres −20, (DTA +5 à l'actif, CP −15 si on raffine). Équilibre ✓.",
"<b>Année 2 — P&L :</b> le décaissement s'impute sur la provision : AUCUNE nouvelle charge comptable. Mais fiscalement, les 20 deviennent déductibles : impôt −5. Résultat net +5 (contre-intuitif : l'année où tu PAIES, ton résultat MONTE).",
"<b>Année 2 — Flux :</b> résultat +5, reprise de provision non-cash −20 (le décaissement réel) → flux opérationnel −15. <b>Bilan :</b> trésorerie −15, provision −20 au passif, capitaux propres +5. Équilibre ✓.",
"<b>Synthèse :</b> la provision découple le moment de la CHARGE (année 1) du moment du CASH (année 2). C'est exactement pour ça que le cookie jar accounting fonctionne — et pour ça que les analystes regardent les reprises de provisions comme du lait sur le feu."
],
coach:"Si l'année 2 t'a surpris (résultat en hausse l'année du paiement), c'est LA subtilité du drill — et une question piège d'entretien avancé. Les provisions sont une machine à voyager dans le temps comptable : maîtrise-la avant qu'on t'interroge dessus."},
{id:"k4", title:"Capex de 100 financé par dette", tag:"Année 0 et année 1",
setup:"Ton entreprise achète une machine 100 M€ le 31 décembre (année 0), financée intégralement par un emprunt à 5 %. Amortissement linéaire sur 10 ans à partir de l'année 1. IS 25 %.",
task:"Déroule les trois états à l'année 0 (jour de l'achat), puis à l'année 1 complète.",
grid:[
"<b>Année 0 — P&L :</b> rien. Aucune charge : un investissement n'est PAS une charge (il le deviendra via l'amortissement). C'est le premier test : beaucoup de candidats mettent −100 au P&L. Éliminatoire.",
"<b>Année 0 — Flux :</b> flux d'investissement −100 (capex), flux de financement +100 (emprunt). Flux net : 0. <b>Bilan :</b> immobilisations +100, dette +100. Équilibre ✓, capitaux propres intacts.",
"<b>Année 1 — P&L :</b> amortissement −10, intérêts −5 → résultat avant impôt −15, impôt +3,75 (économie), résultat net −11,25.",
"<b>Année 1 — Flux :</b> RN −11,25 + amortissement +10 = flux opérationnel −1,25 (les intérêts et l'impôt sont bien cash). <b>Bilan :</b> immobilisations 90 (−10), trésorerie −1,25 → actif −11,25 ; capitaux propres −11,25 ; dette inchangée à 100 (hors remboursement du principal). Équilibre ✓.",
"<b>Synthèse :</b> le capex traverse les flux le jour J et le P&L pendant 10 ans. C'est le décalage fondamental qui rend l'EBITDA menteur sur les entreprises capital-intensives : il ignore la machine qui s'use ET l'intérêt qui la finance."
],
coach:"Le point différenciant : avoir séparé année 0 (bilan et flux seulement) et année 1 (le P&L s'éveille). Si tu as mis le capex en charge, refais le drill maintenant — cette erreur-là ne pardonne dans aucun entretien."},
{id:"k5", title:"Dépréciation de goodwill de 50", tag:"Non-cash, non déductible",
setup:"Suite à un test d'impairment raté, ton groupe déprécie 50 M€ de goodwill. La dépréciation de goodwill n'est PAS déductible fiscalement. IS 25 %.",
task:"Déroule les trois états. En quoi ce cas diffère-t-il d'un amortissement classique ?",
grid:[
"<b>P&L :</b> charge de dépréciation −50 → résultat avant impôt −50. Impôt : ZÉRO changement (non déductible — contrairement à l'amortissement du drill k1). Résultat net −50, plein pot.",
"<b>Flux :</b> RN −50, réintégration de la dépréciation non-cash +50 → flux opérationnel 0. Pas un euro n'a bougé aujourd'hui.",
"<b>Bilan :</b> goodwill −50 à l'actif, capitaux propres −50. Équilibre ✓.",
"<b>La différence clé avec k1 :</b> l'amortissement déductible CRÉE du cash (bouclier fiscal) ; l'impairment de goodwill n'en crée pas (pas de déduction). Résultat massacré, cash intact, aucun bouclier — le pire des deux mondes comptables.",
"<b>La lecture d'analyste :</b> le cash n'a pas bougé AUJOURD'HUI, mais l'impairment avoue que le cash dépensé À L'ACQUISITION ne reviendra pas. « Non-cash » ne veut pas dire « sans importance » : c'est la reconnaissance différée d'une destruction de valeur bien réelle."
],
coach:"Deux pièges dans ce drill : l'impôt (qui ne bouge pas, contrairement au réflexe) et l'interprétation (« c'est non-cash donc on s'en fiche » = la phrase qui te grille face à un bon interviewer). L'impairment est le reçu d'un argent déjà brûlé."},
{id:"k6", title:"Le DSO dérape de 30 jours", tag:"BFR pur",
setup:"Ton CA est de 365 M€ (soit 1 M€/jour, comme par hasard). Tes clients passent de 60 à 90 jours de paiement. Aucun autre changement.",
task:"Déroule l'impact sur les trois états. Puis réponds : que dira l'EBITDA ? Et pourquoi est-ce dangereux ?",
grid:[
"<b>P&L :</b> RIEN. Zéro impact. Le CA est inchangé, les charges aussi. L'EBITDA, la marge, le résultat : identiques au centime. C'est tout le problème.",
"<b>Flux :</b> créances clients +30 M€ (30 jours × 1 M€/jour) → variation de BFR défavorable de 30 → flux opérationnel −30 M€.",
"<b>Bilan :</b> créances +30, trésorerie −30. Actif inchangé en total, mais sa composition s'est dégradée : du cash s'est transformé en promesses de clients.",
"<b>Le danger :</b> un P&L parfaitement immobile peut cacher une hémorragie de trésorerie. 30 M€ de cash en moins, c'est peut-être une échéance de dette qu'on ne passe plus — et l'EBITDA n'aura rien vu. C'est aussi un signal : des clients qui paient plus tard, c'est parfois TES ventes forcées en fin de trimestre (channel stuffing) ou LEURS difficultés qui commencent.",
"<b>L'ordre de grandeur à mémoriser :</b> 1 jour de DSO = CA/365 de cash. Sur 365 M€ de CA, chaque jour vaut 1 M€. La relance clients est littéralement l'activité la mieux payée de l'entreprise."
],
coach:"Le test caché de ce drill : as-tu dit spontanément que le P&L ne bouge PAS ? Les candidats moyens inventent un impact au résultat. Les bons savent que le BFR est invisible au P&L — c'est exactement pour ça qu'il tue en silence."},
{id:"k7", title:"Stock acheté cash, vendu à crédit", tag:"Cycle complet",
setup:"Mois 1 : tu achètes 60 de marchandises, payées cash. Mois 2 : tu les vends 100, encaissables à 60 jours. Mois 4 : le client paie. IS 25 % payé au mois de la vente (simplification).",
task:"Déroule le cycle complet en trois temps : à l'achat, à la vente, à l'encaissement. Suis le cash à la trace.",
grid:[
"<b>Mois 1 (achat) :</b> P&L : rien (le stock n'est pas une charge). Flux : −60 (BFR : stock +60). Bilan : stock +60, trésorerie −60. Tu as déjà décaissé, aucun revenu en face.",
"<b>Mois 2 (vente) :</b> P&L : CA +100, coût des ventes −60 (le stock devient charge AU MOMENT de la vente), marge +40, impôt −10, RN +30. Flux : RN +30, stock −60 (réintégré, favorable), créances +100 (défavorable) → flux = 30 + 60 − 100 = −10. Bilan : stock 0, créances +100, trésorerie −70 cumulée, CP +30. ✓",
"<b>Mois 4 (encaissement) :</b> P&L : rien (le profit a déjà été reconnu). Flux : créances −100 → flux +100. Bilan : créances 0, trésorerie +30 en cumulé depuis le début. ✓",
"<b>La lecture du cycle :</b> le profit total (+30) n'arrive en cash qu'au mois 4, mais l'entreprise a passé 3 mois avec un trou de trésorerie allant jusqu'à −70. Multiplie ça par la croissance : chaque nouveau cycle de vente exige d'avancer 60 + l'impôt avant d'encaisser. Le financement du CYCLE est un métier en soi — c'est le crédit court terme, l'affacturage, et la raison d'être du banquier d'entreprise."
],
coach:"Ce drill est le condensé de toute la mécanique BFR. Si tu sais le dérouler sans hésiter, avec les trois états à chaque étape, tu es au niveau des candidats du top decile sur cette question. Sinon : trois jours, et il revient."},
{id:"k8", title:"Signature d'un bail IFRS 16", tag:"IFRS 16",
setup:"Ton entreprise signe un bail de bureaux : 10 ans fermes, 10 M€/an. Taux d'actualisation : 5 %. La valeur actualisée des loyers est d'environ 77 M€. Compare l'ancien monde (pré-IFRS 16) et le nouveau.",
task:"Déroule l'impact à la signature et sur l'année 1, dans les deux référentiels. Que devient l'EBITDA ?",
grid:[
"<b>Ancien monde (pré-2019) :</b> à la signature : rien nulle part. Année 1 : loyer −10 en charge opérationnelle → EBITDA −10. Bilan : rien (l'engagement de 100 M€ sur 10 ans vit dans les annexes, que personne ne lit).",
"<b>Nouveau monde, à la signature :</b> P&L : rien. Bilan : droit d'usage +77 à l'actif, dette de loyers +77 au passif. Ta « dette » vient de bondir de 77 M€ sans qu'un banquier soit entré dans la pièce.",
"<b>Nouveau monde, année 1 — P&L :</b> plus de loyer en opex. À la place : amortissement du droit d'usage −7,7 (77/10) et intérêts −3,85 (5 % × 77). Total ≈ −11,5 en année 1 (plus lourd que le loyer au début, plus léger à la fin — le profil est frontloadé). <b>EBITDA : IMPACT ZÉRO</b> — amortissement et intérêts en sont exclus. L'EBITDA est +10 plus haut que dans l'ancien monde.",
"<b>Flux :</b> le décaissement réel reste 10/an, mais il se reclasse : ~3,85 en intérêts (opérationnel ou financement selon l'option) et ~6,15 en remboursement de dette de loyers (financement) → le flux OPÉRATIONNEL s'améliore optiquement aussi.",
"<b>Synthèse d'analyste :</b> même bail, même cash, mais EBITDA +10, dette +77 et flux opérationnel embelli. Toute comparaison de multiples, de levier ou de conversion de cash entre référentiels (ou entre une entreprise locataire et une propriétaire) exige un retraitement. Le chiffre n'a pas changé de réalité, seulement de costume."
],
coach:"Le point à avoir verbalisé : l'EBITDA ne capte PLUS le coût immobilier d'une entreprise locataire. Si tu compares un distributeur locataire (EBITDA gonflé) à un propriétaire sans retraiter, tu te trompes de 20-30 % — et en M&A, cette erreur se paie en centaines de millions."}
];

// ---- PAPER LBO : l'exercice de screening PE, à dérouler de tête ----
const PLBO = [
{id:"p1", title:"Le paper LBO canonique", tag:"5 minutes, de tête",
setup:"Un fonds achète une cible : EBITDA 50 M€, multiple d'entrée 8× EV/EBITDA, financement 60 % dette / 40 % equity. En 5 ans, l'EBITDA passe à 70 M€, le fonds rembourse 100 M€ de dette, et sort au même multiple de 8×.",
task:"Déroule : EV d'entrée, structure, EV de sortie, equity de sortie, MOIC, et TRI approximatif. De tête, comme en entretien — écris ton raisonnement étape par étape.",
grid:[
"<b>Entrée :</b> EV = 50 × 8 = 400. Dette = 240 (60 %), equity investie = 160 (40 %).",
"<b>Sortie :</b> EV = 70 × 8 = 560. Dette restante = 240 − 100 = 140. Equity de sortie = 560 − 140 = 420.",
"<b>MOIC :</b> 420 / 160 = ×2,6.",
"<b>TRI approximatif (les repères à connaître par cœur) :</b> ×2 en 5 ans ≈ 15 %, ×2,5 ≈ 20 %, ×3 ≈ 25 %. Donc ×2,6 ≈ 21 %. Réponse d'entretien : « environ 20-21 % ».",
"<b>La décomposition de la création de valeur (le bonus qui te distingue) :</b> croissance d'EBITDA : (70−50) × 8 = +160 d'EV. Désendettement : +100. Expansion de multiple : 0 (entrée = sortie). Total : +260 d'equity (160 → 420). ✓ Les deux tiers viennent de l'opérationnel, un tiers du levier — c'est le profil d'un bon deal."
],
coach:"La vitesse compte : cet exercice se déroule en 4-5 minutes chrono en entretien de PE. Les trois repères MOIC→TRI (×2≈15 %, ×2,5≈20 %, ×3≈25 % sur 5 ans) doivent être des réflexes. Et la décomposition finale est ce qui sépare le candidat correct du candidat mémorable."},
{id:"p2", title:"Contraction de multiple", tag:"Le vent de face",
setup:"Même deal que p1 (EBITDA 50 → 70, entrée 8×, dette 240 → 140), mais le marché s'est retourné : la sortie se fait à 7× au lieu de 8×.",
task:"Recalcule equity de sortie, MOIC, TRI approximatif. Puis réponds : quelle croissance d'EBITDA aurait-il fallu pour compenser entièrement la contraction ?",
grid:[
"<b>Sortie :</b> EV = 70 × 7 = 490. Equity = 490 − 140 = 350. MOIC = 350/160 = ×2,2 → TRI ≈ 17 %.",
"<b>Le coût du point de multiple :</b> 1× de moins sur 70 d'EBITDA = 70 M€ d'equity en moins, soit 0,44× de MOIC et ~4 points de TRI. Le multiple de sortie est la variable la plus violente du modèle — et la moins contrôlable.",
"<b>Compensation par l'EBITDA :</b> pour retrouver 560 d'EV à 7×, il faut 80 d'EBITDA (560/7). Soit +60 % de croissance au lieu de +40 % — un tiers d'effort opérationnel EN PLUS juste pour neutraliser 1× de marché.",
"<b>La leçon d'investissement :</b> un cas d'investissement qui a BESOIN de l'expansion de multiple pour atteindre son TRI cible n'est pas un plan, c'est un pari sur le cycle. Les comités d'investissement sérieux modélisent la sortie au multiple d'entrée, voire un cran en dessous — la contraction est le scénario de base prudent, l'expansion un bonus."
],
coach:"Retiens l'asymétrie psychologique : tout le monde modélise l'expansion de multiple en haut de cycle (« le marché paiera 9× ») et personne ne modélise la contraction. Les millésimes 2006-07 sont morts exactement de ça. Ton réflexe : sortie ≤ entrée, toujours."},
{id:"p3", title:"Du FCF au désendettement", tag:"D'où vient le remboursement",
setup:"Cible : EBITDA 50 stable, capex 10/an, BFR stable, dette initiale 240 à 6 % d'intérêt, IS 25 %. Le fonds veut savoir combien de dette sera remboursée en 5 ans.",
task:"Calcule le FCF disponible pour le service de la dette d'une année type, puis le désendettement total sur 5 ans (ignore la baisse progressive des intérêts pour simplifier, puis corrige en ordre de grandeur).",
grid:[
"<b>Année type :</b> EBITDA 50 − capex 10 = 40. Intérêts : 240 × 6 % = 14,4. Base imposable ≈ EBITDA − amortissements (~10) − intérêts = 25,6 → impôt ≈ 6,4. FCF pour rembourser ≈ 50 − 10 − 14,4 − 6,4 = <b>~19 M€/an</b>.",
"<b>Sur 5 ans (statique) :</b> ~95 M€ remboursés. <b>Correction dynamique :</b> chaque remboursement réduit les intérêts de l'année suivante (~1,15 M€ d'intérêts en moins par tranche de 19 remboursée) → le rythme accélère : réaliste ≈ 100-105 M€. Voilà d'où venaient les « 100 de dette remboursée » du drill p1 — ce n'était pas un chiffre magique.",
"<b>Le ratio à vérifier :</b> dette initiale / FCF de remboursement = 240/19 ≈ 12+ ans pour tout rembourser. Un LBO ne rembourse JAMAIS tout : il rembourse 40-50 % et compte sur la croissance d'EBITDA et la sortie. Si ton paper LBO montre un remboursement intégral en 5 ans, tu as une erreur (ou une cible miraculeuse).",
"<b>Sensibilité à connaître :</b> si l'EBITDA baisse de 20 % (40 au lieu de 50), le FCF tombe à ~11 : le désendettement s'effondre de moitié, et le levier (dette/EBITDA) BONDIT par les deux bouts du ratio. C'est la double peine du levier en bas de cycle."
],
coach:"Ce drill teste si tu sais D'OÙ vient le cash d'un LBO — la plupart des candidats savent faire p1 mais s'effondrent quand on demande « et les 100 de remboursement, ils viennent d'où ? ». Sache toujours reconstruire le FCF ligne à ligne : EBITDA − capex − intérêts − impôts − ΔBFR."},
{id:"p4", title:"Le dividend recap en cours de route", tag:"Sortir du cash sans vendre",
setup:"Reprends p1 : entrée EV 400, dette 240, equity 160. Fin d'année 2 : EBITDA déjà à 60, dette réduite à 200. Le fonds refinance : nouvelle dette à 4× l'EBITDA (240), et la différence lui est versée en dividende. La sortie reste en année 5 : EBITDA 70, multiple 8×, et d'ici là 80 de dette sont remboursés sur la nouvelle souche.",
task:"Calcule le dividende du recap, puis le MOIC total du fonds (dividende + equity de sortie). Qu'est-ce que ça change au profil de risque ?",
grid:[
"<b>Le recap (fin année 2) :</b> nouvelle dette = 4 × 60 = 240. Dette actuelle 200 → dividende au fonds = 40. Le fonds a récupéré 40 sur ses 160 investis (25 % de la mise) sans rien vendre.",
"<b>Sortie (année 5) :</b> EV = 70 × 8 = 560. Dette = 240 − 80 = 160. Equity = 400.",
"<b>MOIC total :</b> (40 + 400) / 160 = ×2,75 — contre ×2,6 sans recap. Et le TRI monte davantage encore (~22-23 %) car les 40 reviennent TÔT : le TRI adore le cash précoce.",
"<b>Ce que ça change :</b> pour le fonds, du risque en moins (une partie de la mise est sécurisée) et un TRI dopé. Pour l'ENTREPRISE, un levier rechargé de 3,3× à 4× en année 2 : la marge d'erreur des trois années suivantes a fondu. Le recap transfère du risque du fonds vers l'entreprise et ses créanciers.",
"<b>La question de gouvernance à soulever :</b> les nouveaux prêteurs du recap financent un dividende, pas un projet. Ils le savent et le pricent (covenants, marge). Quand les recaps se multiplient dans le marché, c'est un marqueur de haut de cycle du crédit — les prêteurs acceptent n'importe quoi."
],
coach:"Le calcul est simple ; l'intelligence du drill est dans la lecture du risque. Si ta réponse n'a pas mentionné que le recap recharge le risque de l'entreprise pendant qu'il sécurise le fonds, tu as fait le calcul du GP sans voir le monde du CFO — or c'est CFO que tu veux devenir."},
{id:"p5", title:"Le build-up qui change tout", tag:"Arbitrage de multiple",
setup:"Ta plateforme : EBITDA 50, achetée 8× (EV 400, dette 240, equity 160). En année 2, elle rachète un concurrent : EBITDA 15, payé 5× (75), financé à 100 % par de la dette nouvelle. À la sortie en année 5 : EBITDA combiné 80 (50 → 62 en organique + 15 + 3 de synergies), multiple de sortie 8×, dette totale restante 250.",
task:"Calcule l'equity de sortie et le MOIC. Puis isole : combien de valeur vient du seul arbitrage de multiple sur l'add-on ?",
grid:[
"<b>Sortie :</b> EV = 80 × 8 = 640. Equity = 640 − 250 = 390. MOIC = 390/160 = <b>×2,44</b> — sans un euro d'equity supplémentaire injecté.",
"<b>L'arbitrage de multiple isolé :</b> l'EBITDA de l'add-on (15) a été acheté 5× (75) et se revend 8× dans l'ensemble (120) → +45 de valeur créée par le simple re-rating, avant toute synergie. Les 3 de synergies ajoutent 3 × 8 = 24. Total build-up : ~69 de valeur pour zéro equity.",
"<b>Pourquoi ça marche :</b> la taille et l'intégration paient — un ensemble de 80 d'EBITDA structuré vaut 8× quand la petite cible isolée n'en valait que 5× (moins liquide, moins d'acheteurs, dépendance au fondateur). C'est le modèle économique dominant du PE mid-cap actuel.",
"<b>Les conditions de validité (à toujours citer) :</b> 1) que l'intégration réussisse (sinon tu as payé 5× un problème) ; 2) que le multiple de plateforme tienne à la sortie ; 3) que la dette d'add-on reste soutenable — ici le levier de sortie est 250/80 ≈ 3,1×, sain. Un build-up raté cumule les trois échecs d'un coup."
],
coach:"Le réflexe pro : décomposer TOUJOURS la création de valeur (organique / arbitrage / synergies / désendettement). Un TRI global peut cacher un build-up qui détruit de la valeur masqué par un bon marché. Celui qui sait décomposer sait où regarder — et c'est lui qu'on embauche."},
{id:"p6", title:"Le prix maximum payable", tag:"Ingénierie inverse",
setup:"Ton comité veut un TRI de 20 % minimum sur 5 ans (soit ~×2,5). Cible : EBITDA 40, croissance crédible vers 52 en 5 ans, sortie prudente à 7×, structure 55 % dette / 45 % equity, et le FCF permettra de rembourser ~70 de dette.",
task:"Ingénierie inverse : quel est le multiple d'entrée MAXIMUM que tu peux payer ? Déroule le raisonnement à rebours.",
grid:[
"<b>Partir de la fin :</b> EV de sortie = 52 × 7 = 364.",
"<b>Poser l'inconnue :</b> soit P le prix d'entrée (EV). Dette initiale = 0,55P, equity = 0,45P. Dette de sortie = 0,55P − 70. Equity de sortie = 364 − 0,55P + 70 = 434 − 0,55P.",
"<b>La contrainte :</b> equity sortie ≥ 2,5 × equity entrée → 434 − 0,55P ≥ 2,5 × 0,45P → 434 ≥ 0,55P + 1,125P = 1,675P → <b>P ≤ 259</b>, soit un multiple d'entrée max de 259/40 ≈ <b>6,5×</b>.",
"<b>La confrontation au réel :</b> si le process est une enchère où les offres tournent à 8× (320), ton TRI tombe : equity entrée 144, equity sortie = 434 − 176 = 258, MOIC ×1,8 ≈ 12-13 %. Sous ton seuil. La réponse du professionnel : on passe, ou on trouve un angle (synergies exclusives, add-ons identifiés) qui change NOS chiffres — pas nos exigences.",
"<b>La leçon cardinale :</b> le prix max se calcule AVANT l'enchère, à froid, depuis le TRI exigé — jamais l'inverse. Celui qui « recalcule » son modèle pour justifier le prix de l'enchère a déjà perdu : il optimise ses hypothèses au lieu de son investissement. C'est la winner's curse en construction."
],
coach:"C'est le drill le plus important des six : il inverse la machine. Tout le monde sait calculer un TRI depuis un prix ; les investisseurs calculent un prix depuis un TRI. Si tu as buté sur l'algèbre, refais-la à l'écrit — elle doit devenir automatique, c'est elle qui te protégera un jour de payer trop cher."}
];

// ---- MISSIONS TERRAIN : le réel, chaque semaine ----
const MISSIONS = [
{id:"w1", title:"Les facteurs de risque d'un géant", desc:"Choisis une société du CAC 40, ouvre son document d'enregistrement universel (URD, sur son site investisseurs), lis la section « facteurs de risque » et liste les 5 risques que TOI tu juges les plus matériels — pas les 5 premiers de la liste.", proof:"Nom de la société + tes 5 risques hiérarchisés, avec une ligne de justification chacun."},
{id:"w2", title:"L'earnings call", desc:"Écoute (ou lis le transcript d') un call de résultats d'une société cotée de ton choix. Note les 3 messages que le management martèle, et LA question d'analyste qui l'a mis en difficulté.", proof:"Société, trimestre, les 3 messages, la question qui pique, et ce que la réponse (ou l'esquive) t'apprend."},
{id:"w3", title:"Le deal de la semaine", desc:"Prends un deal M&A annoncé récemment dans la presse (Les Échos, FT). Reconstitue : prix, multiple implicite (cherche l'EBITDA de la cible), logique stratégique annoncée, mode de financement, et réaction du cours de l'acquéreur.", proof:"Les 5 éléments + ton verdict personnel en 3 lignes : bon deal ou winner's curse ?"},
{id:"w4", title:"Le modèle 3 états", desc:"Dans Excel, construis un modèle 3 états sur 5 ans d'une entreprise simple (fictive ou réelle) : P&L, tableau de flux, bilan, BOUCLÉS (le bilan doit équilibrer chaque année via la trésorerie). C'est le rite de passage.", proof:"Décris ta structure d'onglets, le mécanisme de bouclage cash, et le bug le plus vicieux que tu as dû corriger."},
{id:"w5", title:"Trois multiples, un secteur", desc:"Choisis un secteur, prends 3 sociétés cotées comparables, calcule leur EV/EBITDA (capi + dette nette / EBITDA, données des derniers comptes). Explique les écarts entre les trois par la croissance, les marges, le risque.", proof:"Le tableau (3 lignes : capi, dette nette, EBITDA, multiple) et ton explication des écarts en 5 lignes."},
{id:"w6", title:"Un chapitre de Vernimmen", desc:"Lis un chapitre du Vernimmen aligné sur ton module en cours dans l'Académie. Fais-en une fiche de 10 lignes maximum : les 3 idées structurantes, 2 formules, 1 chose qui t'a surpris.", proof:"Le chapitre choisi et ta fiche de 10 lignes."},
{id:"w7", title:"La semaine des taux", desc:"Chaque jour de la semaine, note l'OAT 10 ans et le Bund 10 ans (n'importe quel site financier). En fin de semaine : amplitude des mouvements, et trouve dans l'actualité CE QUI les a fait bouger (données d'inflation, banque centrale, politique).", proof:"Tes relevés quotidiens et l'explication des mouvements de la semaine en 5 lignes."},
{id:"w8", title:"Le DCF réel", desc:"Fais un DCF rapide d'une société cotée dans Excel : FCF projetés 5 ans (hypothèses simples mais écrites), WACC estimé, valeur terminale, bridge vers l'equity. Compare ta valeur au cours actuel.", proof:"Tes hypothèses clés (croissance, marge, WACC, g), ta valeur par action vs le cours, et QUELLE hypothèse expliquerait l'écart."},
{id:"w9", title:"Dix pages de prospectus", desc:"Trouve une note d'opération ou un prospectus d'IPO récent (site AMF, rubrique visas). Lis les 10 premières pages + la section « utilisation du produit de l'émission ». Qui vend, qui encaisse, pour quoi faire ?", proof:"L'opération, la répartition primaire/secondaire (argent pour la boîte vs sortie d'actionnaires), et ce que ça t'apprend sur les motivations réelles."},
{id:"w10", title:"Critique de slides", desc:"Prends la présentation investisseurs des derniers résultats annuels d'un groupe coté. Choisis 3 slides et critique-les en analyste : qu'est-ce qu'on met en avant, qu'est-ce qu'on enterre, quel chiffre manque volontairement ?", proof:"Les 3 slides (numéros/titres) et ta critique — cherche ce que la slide veut que tu ne calcules pas."},
{id:"w11", title:"Paper LBO sur cible réelle", desc:"Choisis une société cotée mid-cap et déroule un paper LBO dessus : EV actuelle, structure possible, FCF disponible, désendettement à 5 ans, sortie au même multiple. Ferait-elle une bonne cible ? Pourquoi (pas) ?", proof:"Ton paper LBO chiffré (6-8 lignes) et ton verdict : cible ou pas, avec les 2 raisons décisives."},
{id:"w12", title:"Deal summary in English", desc:"Pick this week's most interesting deal and write a 15-line summary in English: parties, price and implied multiple, strategic rationale, financing, expected timeline and conditions. Investment-bank memo style: factual, dense, no fluff.", proof:"Your 15 lines in English. Write it as if a VP will read it before a client call."},
{id:"w13", title:"Le spread qui parle", desc:"Trouve le rendement d'une obligation d'un émetteur high yield connu (via un site financier ou la presse) et compare-le à un émetteur investment grade du même secteur, et à l'OAT. Décompose : combien pour le temps, combien pour le risque ?", proof:"Les 3 rendements, les 2 spreads, et ta lecture : le marché price quel niveau d'inquiétude ?"},
{id:"w14", title:"L'avis motivé d'une OPA", desc:"Sur le site de l'AMF, trouve une offre publique récente et lis l'avis motivé du conseil d'administration de la cible + les conclusions de l'expert indépendant. Comment justifient-ils que le prix est équitable ?", proof:"L'opération, les méthodes de valorisation retenues par l'expert, la prime offerte, et une chose qui t'a semblé discutable."},
{id:"w15", title:"Trois méthodes, de tête, puis vérifie", desc:"Choisis une société que tu connais bien. DE TÊTE d'abord : estime sa valeur par multiples, par DCF grossier, et par comparaison de transactions. PUIS vérifie avec les vrais chiffres. Mesure ton écart.", proof:"Tes 3 estimations de tête, les chiffres réels, ton écart en %, et ce qui explique ta plus grosse erreur d'intuition."},
{id:"w16", title:"Parle à un vrai financier", desc:"Décroche 30 minutes avec quelqu'un qui travaille en finance (alumni de ton école, LinkedIn, famille élargie) — ou, à défaut cette semaine, prépare et écris les 10 questions exactes que tu poseras. Des vraies questions, pas « c'est comment le M&A ? ».", proof:"Le compte rendu de l'échange (3 apprentissages) OU tes 10 questions — précises, documentées, qui montrent que tu as fait tes devoirs."}
];

// ---- ENTRETIEN EN ANGLAIS : la banque de questions classiques d'IB, en VO ----
const ENGQ = [
{q:"Walk me through a DCF. What is the correct sequence?", opts:["Pick a multiple, apply it to net income, subtract debt","Project unlevered free cash flows, discount them at WACC, add a discounted terminal value to get EV, then subtract net debt to reach equity value","Discount dividends at the risk-free rate and add back capex","Average the 52-week high and low share prices"], a:1, exp:"The canonical answer: FCF projection (5-10 years) → discount at WACC → terminal value (Gordon growth or exit multiple) → sum = enterprise value → bridge to equity value (minus net debt, minorities). Say it in this order, confidently, in under a minute."},
{q:"Why can't you use EV/Net Income as a multiple?", opts:["Net income is too volatile","Numerator and denominator serve different capital providers: EV belongs to all investors while net income belongs only to shareholders (it is after interest)","Net income is not audited","You can, it is a standard multiple"], a:1, exp:"Consistency rule: EV pairs with metrics BEFORE interest (EBITDA, EBIT, revenue); equity value pairs with metrics AFTER interest (net income, EPS). Mixing them makes two identical firms with different leverage look differently valued."},
{q:"Depreciation increases by $10. Tax rate is 25%. What happens to cash?", opts:["Cash decreases by $10","Cash increases by $2.5: net income falls $7.5, but adding back the non-cash $10 leaves operating cash flow up by the tax shield","Cash is unchanged, depreciation is non-cash","Cash increases by $10"], a:1, exp:"The classic three-statement question. P&L: EBIT −10, tax −2.5, NI −7.5. Cash flow: −7.5 + 10 = +2.5. Balance sheet: PP&E −10, cash +2.5, equity −7.5. It balances. Rehearse until automatic."},
{q:"If you could only pick one financial statement to assess a company's health, which one?", opts:["The income statement — profit is what matters","The cash flow statement: cash is hardest to manipulate and companies die from running out of cash, not from accounting losses","The balance sheet — it shows everything","The auditor's report"], a:1, exp:"Expected answer: cash flow statement, with this reasoning. Strong candidates add: 'ideally the balance sheet plus footnotes for solvency, but for HEALTH, show me the cash.'"},
{q:"What is the formula for Enterprise Value?", opts:["Market cap + cash − debt","Market cap + net debt + minority interests + preferred stock − investments in associates","Total assets − total liabilities","Revenue × industry multiple"], a:1, exp:"EV = equity value + net debt + minorities + preferred − associates/equity investments. The logic: add every claim that 'consumes' the operating metrics, remove assets whose value isn't in those metrics."},
{q:"Why do acquirers pay a control premium?", opts:["Because regulators require it","Because control lets you change management, capture synergies and redirect cash flows — rights a minority shareholder never gets","Because target boards are greedy","To make the deal accretive"], a:1, exp:"Control is an option on doing things differently: typically worth 20-40% above the undisturbed price. Follow-up trap: that's why transaction multiples exceed trading multiples — never mix them."},
{q:"What makes an attractive LBO candidate?", opts:["High growth and high capex, to maximize upside","Stable predictable cash flows, low capex needs, defensible market position, low existing leverage, and identifiable operational improvements","A distressed company with maximum leverage already in place","A biotech with a promising pipeline"], a:1, exp:"Debt service needs boring reliability: recurring revenue, low cyclicality, low capital intensity. Bonus points for mentioning strong management and multiple exit routes."},
{q:"How does debt paydown create equity value in an LBO?", opts:["It doesn't — only EBITDA growth matters","At constant EV, every dollar of debt repaid shifts one dollar from creditors to shareholders: equity = EV − net debt","It lowers the exit multiple","It increases revenue"], a:1, exp:"The mechanical driver: EV fixed at exit, less debt = more equity. Combined with EBITDA growth and (hopefully not required) multiple expansion, these are the three LBO return drivers."},
{q:"What are the components of WACC?", opts:["Risk-free rate plus inflation","Cost of equity (via CAPM) weighted by equity share, plus after-tax cost of debt weighted by debt share, at target capital structure","The average interest rate on the company's loans","Dividend yield plus growth rate"], a:1, exp:"WACC = (E/V)×Ke + (D/V)×Kd×(1−t). Ke via CAPM: risk-free + beta × equity risk premium. Mention 'target structure' and the tax shield to score full points."},
{q:"Why do you unlever and relever beta?", opts:["To correct data errors in Bloomberg","Because comparable companies carry different leverage: you strip out their capital structure (unlever), average the pure business risk, then apply the target's own structure (relever)","To increase the valuation","Betas never need adjustment"], a:1, exp:"Beta observed in the market mixes business risk with financial risk. Unlevering isolates asset beta; relevering applies your target's debt profile. Standard formula: βu = βl / (1 + (1−t)×D/E)."},
{q:"An all-stock deal: acquirer trades at 20x P/E, target is bought at 14x. Accretive or dilutive?", opts:["Dilutive","Accretive: the acquirer pays with 'expensive' shares for 'cheaper' earnings — when acquirer P/E exceeds the P/E paid, EPS rises","Neutral","Cannot say without the WACC"], a:1, exp:"All-stock rule of thumb: accretive if acquirer P/E > deal P/E. Then add the killer caveat: accretion is arithmetic, not value creation — overpaying can still be accretive with cheap financing."},
{q:"An increase in working capital — what does it do to cash flow?", opts:["Increases it","Decreases it: more inventory and receivables (or fewer payables) means cash trapped in the operating cycle","No impact","Depends on the tax rate"], a:1, exp:"ΔWC up = cash down. Growth consumes cash through working capital even when profitable — the overtrading trap. Interviewers love asking why a profitable, fast-growing company can go bankrupt."},
{q:"Your DCF's terminal value is 80% of total value. Is the analysis wrong?", opts:["Yes, redo it with more years","Not necessarily — it is common, but it means the valuation rests on perpetuity assumptions (g, WACC), so run sensitivities and keep g at or below long-term GDP growth","Yes, terminal value must stay below 50%","The DCF should be replaced by multiples"], a:1, exp:"Standard for growing businesses. The right response is intellectual honesty: acknowledge the sensitivity, show the WACC×g matrix, cap g at ~2%. Saying 'my DCF gives exactly $47.32' is the real red flag."},
{q:"Why are IPOs systematically underpriced?", opts:["Banks are bad at math","Investors demand a discount for the uncertainty of an unseasoned issuer, and a strong first day is strategically necessary for liquidity, coverage and future raises","Regulators impose a discount","They are not — most IPOs fall on day one"], a:1, exp:"The 10-15% discount is 'money left on the table' bought deliberately: a broken deal (below issue price) haunts the stock for years. Mention the incentive tension: issuers want high, banks' investor clients want low."},
{q:"Interest rates rise. What happens to bond prices, and why?", opts:["They rise with rates","They fall: existing bonds with lower coupons must discount their price so their yield matches new issues — the longer the duration, the bigger the fall","Nothing, coupons are fixed","Only government bonds fall"], a:1, exp:"Inverse price-yield relationship, scaled by duration (~1% price move per year of duration per 1% rate move). Bonus: this is exactly what killed Silicon Valley Bank in 2023."},
{q:"What is goodwill and when does it appear?", opts:["The value of the company's brand, recorded annually","The excess of purchase price over the fair value of identifiable net assets acquired — created only in acquisitions, tested annually for impairment","A reserve required by regulators","Deferred revenue from loyal customers"], a:1, exp:"Goodwill only arises in M&A (purchase accounting). Under IFRS/US GAAP it is not amortized but impairment-tested. A write-down is the accounting confession of having overpaid — AOL's $99bn is the textbook case."},
{q:"What are the three drivers of LBO returns?", opts:["Luck, timing and leverage","Debt paydown, EBITDA growth, and multiple expansion — with disciplined funds underwriting only the first two","Synergies, taxes and dividends","Revenue, margin and headcount"], a:1, exp:"Say the three, then the judgment: multiple expansion depends on the market, not on you. A deal that NEEDS exit multiple > entry multiple to hit target returns is a cycle bet, not an investment case."},
{q:"What is an earn-out and what is its main problem?", opts:["A retention bonus for employees","Deferred conditional consideration tied to future performance — structurally conflictual because the BUYER controls the business that determines whether the SELLER gets paid","A tax optimization scheme","A form of vendor financing with fixed interest"], a:1, exp:"Bridge for valuation gaps, but the debtor holds the steering wheel: cost allocations, perimeter changes and deferred revenues can kill the target metrics. Protections: simple auditable metrics, conduct covenants, acceleration clauses."},
{q:"What is a MAC clause and how do courts treat it?", opts:["A price adjustment formula","A clause letting the buyer walk if a material adverse change hits the target between signing and closing — courts construe it very narrowly, requiring severe, durable, company-specific impact","An antitrust commitment","A financing condition"], a:1, exp:"Delaware has upheld a MAC essentially once (Akorn, 2018). Sector-wide shocks (COVID) rarely qualify absent disproportionate impact — which is why LVMH settled for a 2.6% discount on Tiffany rather than litigate."},
{q:"Locked box vs completion accounts — the key difference?", opts:["Currency of payment","Locked box fixes the price on a past reference balance sheet protected by anti-leakage covenants; completion accounts adjust the price on actual closing-date figures","Locked box is only for real estate","Completion accounts skip due diligence"], a:1, exp:"Locked box = price certainty, seller-friendly, dominant in European auctions. Completion accounts = precision but post-closing disputes. Knowing when each is used signals real deal exposure."},
{q:"Cash vs stock consideration: what does the choice signal about risk?", opts:["Nothing, it is a financing detail","Cash means the buyer keeps all the risk (and upside) of the deal; stock makes the seller share post-closing risk — and paying with stock may signal the buyer thinks its own shares are fully valued","Stock deals are always better for the seller","Cash deals require regulatory approval"], a:1, exp:"AOL paid with inflated paper (sellers shared the crash); Bayer paid cash for Monsanto (kept 100% of the glyphosate risk). The consideration mix IS a risk-allocation and signaling decision."},
{q:"Using the rule of 72: how long to double your money at 9%?", opts:["9 years","8 years: 72 divided by 9","12 years","6 years"], a:1, exp:"72/rate ≈ doubling time. Works remarkably well between 4% and 15%. Follow-up they love: quadrupling = two doublings = 16 years."},
{q:"What does an inverted yield curve signal?", opts:["Imminent inflation","Markets expect the central bank to cut rates — i.e., a slowdown or recession ahead; it has preceded most modern US recessions","A currency crisis","Nothing reliable"], a:1, exp:"Short rates above long rates = the market prices future cuts. Not magic: the aggregated forecast of millions of investors. For a CFO: secure liquidity, extend maturities, prepare for buyer-friendly M&A later."},
{q:"Company A has EV/EBITDA of 12x, Company B of 8x, same sector. Is B cheaper?", opts:["Yes, obviously — 8 is less than 12","Not necessarily: a multiple compresses growth, returns and risk into one number — B may deserve 8x due to lower growth or ROCE; compare multiples only after comparing fundamentals","Yes, unless B has more debt","Multiples cannot be compared within a sector"], a:1, exp:"The trap of 'cheap'. A multiple is a shorthand DCF: 12x with double the growth and better ROCE can be the better buy. Always ask WHY the multiple differs before calling anything cheap — value traps live at 8x."}
];
