// LE CLOSING — Lexique FR/EN du deal-maker
// Format : {t: terme, en: équivalent anglais, cat, d: définition}
const LEXIQUE = [
{t:"EBITDA", en:"EBITDA", cat:"Compta", d:"Excédent brut d'exploitation : résultat avant intérêts, impôts, amortissements. Proxy de cash opérationnel, base des multiples et covenants — mais PAS du cash."},
{t:"Valeur d'entreprise", en:"Enterprise value (EV)", cat:"Valo", d:"Valeur de l'outil économique, tous financeurs confondus : capitalisation + dette nette (+ minoritaires, provisions). Se compare à l'EBITDA/EBIT, jamais au résultat net."},
{t:"Valeur des capitaux propres", en:"Equity value", cat:"Valo", d:"Ce qui revient aux actionnaires : EV − dette nette. C'est le prix des actions."},
{t:"Dette nette", en:"Net debt", cat:"Compta", d:"Dettes financières − trésorerie. En M&A, élargie aux debt-like items (retraites, litiges, earn-outs dus)."},
{t:"BFR", en:"Working capital", cat:"Compta", d:"Stocks + créances clients − dettes fournisseurs : le cash immobilisé dans le cycle d'exploitation. La croissance le gonfle, donc consomme du cash."},
{t:"Flux de trésorerie disponible", en:"Free cash flow (FCF)", cat:"Compta", d:"Cash opérationnel − capex : l'argent réellement disponible pour la dette, les dividendes, les acquisitions. Le chiffre du DCF et du LBO."},
{t:"DCF", en:"Discounted cash flow", cat:"Valo", d:"Valorisation par actualisation des flux futurs au WACC. Donne la cohérence entre un prix et des hypothèses — jamais un chiffre unique."},
{t:"WACC", en:"Weighted average cost of capital", cat:"Valo", d:"Coût moyen pondéré du capital : rendement minimal exigé par actionnaires et créanciers. Taux d'actualisation du DCF et barre du ROCE."},
{t:"Valeur terminale", en:"Terminal value", cat:"Valo", d:"Valeur au-delà de l'horizon explicite du DCF : FCF × (1+g)/(WACC−g). Pèse souvent 60-80 % du total — d'où l'analyse de sensibilité obligatoire."},
{t:"Bêta", en:"Beta", cat:"Valo", d:"Sensibilité d'un titre aux mouvements du marché (risque non diversifiable). Brique du CAPM pour le coût des fonds propres."},
{t:"Multiple", en:"Multiple", cat:"Valo", d:"Raccourci de valorisation : EV/EBITDA (le roi), P/E… Cohérence obligatoire entre numérateur et dénominateur (mêmes pourvoyeurs de fonds)."},
{t:"Comparables boursiers", en:"Trading comps", cat:"Valo", d:"Multiples de sociétés cotées similaires. Valorisation minoritaire : sans prime de contrôle."},
{t:"Transactions précédentes", en:"Precedent transactions", cat:"Valo", d:"Multiples payés dans des deals M&A comparables. Incluent la prime de contrôle : plus élevés que les trading comps."},
{t:"Prime de contrôle", en:"Control premium", cat:"Valo", d:"Surprix (20-40 %) payé pour le pouvoir de décider : changer le management, capter les synergies."},
{t:"Relutif / dilutif", en:"Accretive / dilutive", cat:"M&A", d:"Effet d'un deal sur le BPA de l'acquéreur. Relutif ≠ créateur de valeur : avec de la dette bon marché, même un surpaiement est relutif."},
{t:"Goodwill", en:"Goodwill", cat:"Compta", d:"Écart entre prix payé et juste valeur des actifs nets identifiables acquis. Testé chaque année ; sa dépréciation avoue un surpaiement."},
{t:"Dépréciation", en:"Impairment", cat:"Compta", d:"Constat comptable (non-cash) qu'un actif ne vaut plus sa valeur au bilan. Traverse le résultat ; le cash, lui, a été détruit au moment de l'achat."},
{t:"ROCE", en:"Return on capital employed", cat:"Analyse", d:"Rentabilité du capital investi dans le métier. ROCE > WACC = création de valeur ; l'inverse en détruit, même en croissance."},
{t:"Covenant", en:"Covenant", cat:"Dette", d:"Ratio contractuel (ex. dette nette/EBITDA < 3,5×) dont la violation permet aux prêteurs d'exiger le remboursement. Sa marge (headroom) compte plus que son niveau."},
{t:"Cov-lite", en:"Covenant-lite", cat:"Dette", d:"Dette sans covenants de maintenance (testés en permanence), seulement d'incurrence (testés lors d'actions). Confort de l'emprunteur, risque du prêteur."},
{t:"Défaut croisé", en:"Cross-default", cat:"Dette", d:"Clause rendant toutes les dettes exigibles dès qu'une seule est en défaut. L'effet domino contractualisé."},
{t:"Changement de contrôle", en:"Change of control", cat:"Dette", d:"Clause rendant la dette exigible en cas de rachat de l'emprunteur. À vérifier chez toute cible : son refinancement fait partie du prix du deal."},
{t:"LBO", en:"Leveraged buyout", cat:"LBO", d:"Rachat par endettement : peu d'equity, beaucoup de dette, remboursée par les cash-flows de la cible elle-même via une holding (NewCo)."},
{t:"Dette senior", en:"Senior debt", cat:"LBO", d:"Premier rang de la dette LBO : la moins chère, la mieux protégée (sûretés), remboursée en premier."},
{t:"Mezzanine", en:"Mezzanine", cat:"LBO", d:"Dette subordonnée entre senior et equity, souvent avec accès au capital (warrants) et intérêts capitalisés (PIK)."},
{t:"Unitranche", en:"Unitranche", cat:"LBO", d:"Tranche unique fusionnant senior et subordonné, fournie par les fonds de dette privée. Plus chère, plus rapide à exécuter."},
{t:"PIK", en:"Payment in kind", cat:"LBO", d:"Intérêts non payés en cash mais ajoutés au principal : préserve la trésorerie, fait boule de neige."},
{t:"TRI", en:"IRR (internal rate of return)", cat:"LBO", d:"Rendement annualisé d'un investissement. Sensible à la durée et manipulable (sorties rapides) — toujours à lire avec le MOIC."},
{t:"MOIC", en:"Multiple on invested capital", cat:"LBO", d:"Multiple sur la mise : cash rendu / cash investi. Insensible au temps — le complément indispensable du TRI."},
{t:"Recap de dividende", en:"Dividend recap", cat:"LBO", d:"Réendetter la participation pour verser un dividende au fonds avant la sortie. Sécurise le fonds, recharge le risque de l'entreprise."},
{t:"Build-up", en:"Build-up / bolt-on", cat:"LBO", d:"Acquisitions de petits concurrents par la participation d'un fonds : arbitrage de multiple (acheter 5×, revalorisé 9× dans l'ensemble)."},
{t:"Management package", en:"Management package", cat:"LBO", d:"Investissement et intéressement des dirigeants dans un LBO (sweet equity, ratchet), avec clauses good/bad leaver."},
{t:"Good / bad leaver", en:"Good / bad leaver", cat:"LBO", d:"Qualification du départ d'un manager : légitime (prix de marché) ou fautif/précoce (prix décoté). Décide s'il part avec ×3 ou zéro."},
{t:"Carried interest", en:"Carried interest", cat:"LBO", d:"Intéressement de l'équipe du fonds (~20 % des plus-values au-delà d'un rendement plancher). Le moteur du private equity."},
{t:"LP / GP", en:"Limited / general partner", cat:"LBO", d:"LP : les investisseurs du fonds (assureurs, fonds de pension). GP : la société de gestion qui investit et gère."},
{t:"Teaser", en:"Teaser", cat:"Process", d:"Document anonyme d'1-2 pages présentant une cible à vendre. Première étape du process sell-side."},
{t:"Mémorandum d'information", en:"CIM / Info memo", cat:"Process", d:"Document détaillé (50-100 p.) remis après NDA : activité, chiffres, business plan de la cible."},
{t:"Offre indicative", en:"IOI / non-binding offer", cat:"Process", d:"Offre de premier tour, non engageante : fourchette de prix, structure, financement envisagé. Sert à être shortlisté."},
{t:"Offre ferme", en:"Binding offer", cat:"Process", d:"Offre engageante de second tour, accompagnée d'un SPA marké et d'un financement documenté."},
{t:"Data room", en:"Data room", cat:"Process", d:"Espace (virtuel) où le vendeur expose les documents de la cible pour la due diligence. Ce qui y est révélé est réputé accepté."},
{t:"Due diligence", en:"Due diligence", cat:"Process", d:"Audit d'acquisition (financier, juridique, fiscal, social...). Alimente le prix, les garanties et la structure — tes munitions contractuelles."},
{t:"VDD", en:"Vendor due diligence", cat:"Process", d:"Due diligence commandée par le vendeur avant le process, remise aux candidats. Fiabilise l'information et accélère l'enchère."},
{t:"Exclusivité", en:"Exclusivity", cat:"Process", d:"Engagement du vendeur de ne négocier qu'avec un seul candidat. L'actif le plus précieux du vendeur : se vend contre prix confirmé et calendrier."},
{t:"Double voie", en:"Dual track", cat:"Process", d:"Mener en parallèle une IPO et une cession M&A pour faire jouer la concurrence entre les deux sorties."},
{t:"LOI", en:"Letter of intent / term sheet", cat:"Juridique", d:"Lettre d'intention : accord de principe non engageant sur le prix, mais aux clauses de cadre (exclusivité, confidentialité) bien engageantes."},
{t:"SPA", en:"Share purchase agreement", cat:"Juridique", d:"Contrat de cession d'actions : prix et ajustements, période intercalaire, garanties, conditions suspensives. Chaque virgule a un prix."},
{t:"Déclarations et garanties", en:"Representations & warranties", cat:"Juridique", d:"Affirmations du vendeur sur la société (comptes, litiges, conformité). Leur violation déclenche l'indemnisation."},
{t:"Garantie d'actif-passif", en:"Indemnity / warranty claim", cat:"Juridique", d:"Mécanisme d'indemnisation de l'acheteur pour les passifs cachés. Négociée via cap, durée, franchise, de minimis."},
{t:"Franchise / seuil", en:"Basket / deductible", cat:"Juridique", d:"Seuil de déclenchement des garanties. Tipping : tout est dû dès le seuil franchi ; deductible : seulement l'excédent. Des millions d'écart."},
{t:"Séquestre", en:"Escrow", cat:"Juridique", d:"Partie du prix bloquée chez un tiers pour sécuriser les réclamations de garantie. Indispensable face à un vendeur qui distribue (fonds)."},
{t:"Assurance W&I", en:"W&I insurance", cat:"Juridique", d:"L'assureur se substitue au vendeur pour indemniser l'acheteur. Standard des sorties de fonds ; exclut les risques identifiés et la fraude."},
{t:"Locked box", en:"Locked box", cat:"Juridique", d:"Prix fixé sur un bilan de référence verrouillé ; toute fuite de valeur (leakage) vers le vendeur est remboursable. Favorable au vendeur."},
{t:"Comptes de closing", en:"Completion accounts", cat:"Juridique", d:"Ajustement du prix sur les comptes établis au jour du closing (dette nette, BFR réels vs cibles). Précis mais contentieux."},
{t:"Complément de prix", en:"Earn-out", cat:"Juridique", d:"Part du prix conditionnée aux performances futures de la cible. Structurellement conflictuel : l'acheteur contrôle ce qui déclenche le paiement."},
{t:"Clause MAC", en:"Material adverse change", cat:"Juridique", d:"Permet de ne pas closer si un événement grave et durable frappe la cible entre signing et closing. Interprétée très restrictivement (cf. LVMH-Tiffany)."},
{t:"Indemnité de rupture", en:"Break-up fee", cat:"Juridique", d:"Somme due si une partie abandonne le deal dans des cas définis. Ne permet PAS de s'échapper à volonté (cf. Musk-Twitter)."},
{t:"Exécution forcée", en:"Specific performance", cat:"Juridique", d:"Droit d'exiger en justice la réalisation du deal lui-même, pas seulement des dommages. La clause qui a forcé Musk à payer."},
{t:"Conditions suspensives", en:"Conditions precedent", cat:"Juridique", d:"Conditions à réaliser entre signing et closing : antitrust, IEF, parfois financement. Elles définissent qui porte quel risque d'exécution."},
{t:"Gun jumping", en:"Gun jumping", cat:"Réglementaire", d:"Mettre en œuvre le rapprochement avant l'autorisation antitrust (échanges sensibles, contrôle de fait). Lourdement sanctionné."},
{t:"Offre publique obligatoire", en:"Mandatory tender offer", cat:"Réglementaire", d:"En France, franchir 30 % du capital ou des droits de vote impose une offre sur 100 % des titres. D'où les prises de position à 29,9 %."},
{t:"Retrait obligatoire", en:"Squeeze-out", cat:"Réglementaire", d:"À 90 %, l'initiateur peut exproprier les minoritaires restants contre indemnisation expertisée. L'aboutissement d'une OPA réussie."},
{t:"Pilule empoisonnée", en:"Poison pill", cat:"Défense", d:"Mécanisme anti-OPA : franchir un seuil déclenche une dilution punitive de l'assaillant. Force la négociation avec le conseil."},
{t:"Chevalier blanc", en:"White knight", cat:"Défense", d:"Acquéreur ami sollicité par la cible pour contrer une offre hostile."},
{t:"Standstill", en:"Standstill", cat:"Défense", d:"Engagement de ne pas acheter de titres de la cible en bourse pendant/après des négociations. Empêche le raid informé."},
{t:"Sortie conjointe", en:"Tag along", cat:"Pacte", d:"Droit du minoritaire de vendre aux mêmes conditions que le majoritaire. Protection contre un changement de contrôle subi."},
{t:"Cession forcée", en:"Drag along", cat:"Pacte", d:"Obligation du minoritaire de vendre quand le majoritaire cède 100 %. Protège la liquidité de l'ensemble."},
{t:"Matières réservées", en:"Reserved matters", cat:"Pacte", d:"Décisions exigeant l'accord d'un actionnaire donné (budget, M&A, dette...). Le contrôle réel se lit là, pas dans les pourcentages."},
{t:"Information privilégiée", en:"Inside information", cat:"Réglementaire", d:"Information précise, non publique, susceptible d'influencer le cours. L'utiliser = délit d'initié ; si elle fuit, l'émetteur doit communiquer sans délai (MAR)."},
{t:"Construction du livre", en:"Bookbuilding", cat:"Marchés", d:"Collecte des intentions d'achat des institutionnels pour fixer le prix d'une IPO ou d'un placement."},
{t:"Surallocation", en:"Greenshoe", cat:"Marchés", d:"Option de ~15 % permettant aux banques de stabiliser le cours après l'IPO."},
{t:"Blocage de cession", en:"Lock-up", cat:"Marchés", d:"Interdiction de vente (90-180 j) pour les actionnaires historiques après une IPO. Son expiration est un événement de marché."},
{t:"Écart de crédit", en:"Credit spread", cat:"Marchés", d:"Prime de rendement au-dessus du taux sans risque, thermomètre en temps réel du risque perçu d'un émetteur."},
{t:"Haut rendement", en:"High yield", cat:"Marchés", d:"Dette notée sous BBB- : risque et rendement élevés. La frontière avec l'investment grade est une falaise réglementaire, pas une marche."},
{t:"Ange déchu", en:"Fallen angel", cat:"Marchés", d:"Émetteur dégradé d'investment grade en high yield : ventes forcées des investisseurs contraints, spread qui saute."},
{t:"Duration", en:"Duration", cat:"Marchés", d:"Sensibilité du prix d'une obligation aux taux : ~1 % de prix par point de duration pour 1 % de taux. Ce qui a tué SVB."},
{t:"AT1 / CoCo", en:"AT1 / contingent convertible", cat:"Marchés", d:"Titre hybride bancaire absorbant les pertes (conversion ou dépréciation, parfois à zéro) en cas de non-viabilité. Le rendement paie exactement ce risque."},
{t:"Cascade de priorité", en:"Waterfall", cat:"Resto", d:"Ordre de remboursement en cas de défaut : new money, senior, unsecured, subordonné, equity. Chaque étage servi avant le suivant."},
{t:"Point de rupture", en:"Fulcrum security", cat:"Resto", d:"La tranche de dette partiellement couverte par la valeur : elle convertit en capital et prend le contrôle de la restructuration."},
{t:"Conversion de créances", en:"Debt-to-equity swap", cat:"Resto", d:"Échange de dette contre du capital : les créanciers deviennent actionnaires, les actionnaires historiques sont dilués ou évincés."},
{t:"Cessation des paiements", en:"Insolvency (cash-flow test)", cat:"Resto", d:"Impossibilité de payer le passif exigible avec l'actif disponible. À déclarer sous 45 jours, sous peine de sanctions personnelles du dirigeant."},
{t:"Mandat ad hoc", en:"Ad hoc mandate", cat:"Resto", d:"Procédure amiable et confidentielle : un mandataire aide à négocier avec les créanciers, l'entreprise reste aux commandes."},
{t:"Conciliation", en:"Conciliation", cat:"Resto", d:"Procédure amiable (≤5 mois) permettant d'homologuer un accord et de privilégier la new money. L'antichambre des grands deals de restructuration français."},
{t:"Sauvegarde", en:"Safeguard (Ch.11-like)", cat:"Resto", d:"Procédure collective préventive : gel du passif avant la cessation des paiements, plan négocié sous protection du tribunal."},
{t:"Prepack", en:"Pre-packaged sale", cat:"Resto", d:"Cession préparée confidentiellement en amiable, exécutée en quelques semaines une fois la procédure ouverte. Minimise la destruction de valeur publique."},
{t:"Argent frais", en:"New money", cat:"Resto", d:"Financement apporté pendant la crise : exige et obtient le premier rang (privilège) et des conditions léonines. En restructuration, le cash frais commande."},
{t:"Détourage", en:"Carve-out", cat:"M&A", d:"Extraction d'une activité d'un groupe pour la céder : périmètre, contrats de transition (TSA), fonctions support à recréer. La complexité cachée des cessions de filiales."},
{t:"Scission", en:"Spin-off", cat:"M&A", d:"Séparation d'une activité distribuée aux actionnaires sous forme de société cotée indépendante. L'arme classique contre les décotes de conglomérat."},
{t:"Crédit-vendeur", en:"Vendor loan", cat:"M&A", d:"Le vendeur finance une partie du prix (paiement différé). Aligne les intérêts et comble un déficit de financement — mais le vendeur devient créancier de son acheteur."},
{t:"Crédit relais", en:"Bridge loan", cat:"Dette", d:"Financement court terme en attendant une levée définitive (obligataire, cession). Utile et dangereux : si le marché se ferme, le pont ne mène nulle part."},
{t:"Syndication", en:"Syndication", cat:"Dette", d:"Répartition d'un crédit entre plusieurs banques. Si le marché se retourne avant la revente, la dette reste « collée » aux arrangeurs (hung deal)."},
{t:"Attestation d'équité", en:"Fairness opinion", cat:"Process", d:"Avis d'un expert indépendant sur le caractère équitable d'un prix. Protège le conseil d'administration — et parfois ne protège que lui."}
];
